name: Cloud Run revision route
description: Routes 100% of the traffic to the given tag or default revision

inputs:
  branch-slug:
    description: Slugified branch name of the pull request
    required: false
  revision:
    description: Revision name that will receive 100% of the traffic
    required: true
  service:
    description: Service name
    required: true

runs:
  using: composite
  steps:
    - name: Cloud Run revision route
      shell: bash
      run: |
        branch_slug="${{ inputs.branch-slug }}"
        revision="${{ inputs.revision }}"
        service="${{ inputs.service }}"

        if [[ -z "$branch_slug" ]]; then
          echo "🔀 Routing 100% production traffic with..."
          echo "     -- Revision ⇒ $revision"

          gcloud run services update-traffic "$service" \
            --to-revisions "$revision=100"
        else
          echo "🔀 Routing 100% preview traffic with..."
          echo "     -- Revision ⇒ $revision"
          echo "     -- Tag ⇒ $branch_slug"

          gcloud run services update-traffic "$service" \
            --set-tags "$branch_slug=$revision"
        fi
