-- Production reference data for the powerlifting exercise catalogue.
INSERT INTO "exercise_roles" ("code", "name", "description")
VALUES
  ('competition', 'Competition', 'The exact competition exercise or closest discipline reference execution.'),
  ('variant', 'Variant', 'A close variation of a competition exercise using a modified constraint, range, tempo, grip, stance, or setup.'),
  ('accessory', 'Accessory', 'A support exercise targeting muscles, weak points, or capacities that transfer to one or more competition exercises.'),
  ('drill', 'Drill', 'A technical or skill-focused exercise used to practice positions, timing, control, or movement quality.')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "disciplines" ("code", "name", "description")
VALUES
  ('powerlifting', 'Powerlifting', 'Strength sport built around the squat, bench press, and deadlift.'),
  ('weightlifting', 'Weightlifting', 'Strength sport built around the snatch and the clean and jerk.'),
  ('streetlifting', 'StreetLifting', 'Strength sport built around weighted calisthenics movements like pull-ups, dips, muscle-ups, and squats.'),
  ('strongman', 'Strongman', 'Strength sport built around odd-object and maximal strength events like atlas stones, farmer’s walks, log press, and yoke carries.'),
  ('calisthenics', 'Calisthenics', 'Bodyweight training discipline built around movements like pull-ups, dips, push-ups, levers, handstands, and muscle-ups.'),
  ('crossfit', 'CrossFit', 'Functional fitness sport built around constantly varied workouts combining weightlifting, gymnastics, and conditioning.'),
  ('hyrox', 'HYROX', 'Fitness racing sport built around running intervals combined with functional workout stations like sled pushes, rowing, lunges, and wall balls.')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
WITH discipline_movement_seed(code, name, description, sort_order) AS (
  VALUES
    ('squat', 'Squat', 'The lower-body competition movement built around knee-dominant barbell strength.', 1),
    ('bench_press', 'Bench press', 'The upper-body competition press performed horizontally from the bench.', 2),
    ('deadlift', 'Deadlift', 'The competition pull from the floor built around hip extension and full-body bracing.', 3)
)
INSERT INTO "discipline_movements" ("discipline_id", "code", "name", "description", "sort_order")
SELECT disciplines."id", discipline_movement_seed.code, discipline_movement_seed.name, discipline_movement_seed.description, discipline_movement_seed.sort_order
FROM discipline_movement_seed
JOIN "disciplines" ON disciplines."code" = 'powerlifting'
ON CONFLICT ("discipline_id", "code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "loading_types" ("code", "name", "description")
VALUES
  ('external_load', 'External load', 'Use when the entered load is the external load moved by the athlete.'),
  ('bodyweight', 'Bodyweight', 'Use when the athlete moves bodyweight without added or assisted external load.'),
  ('bodyweight_plus_external', 'Bodyweight plus external load', 'Use when the athlete moves bodyweight plus an added external load.'),
  ('assisted_bodyweight', 'Assisted bodyweight', 'Use when assistance reduces the bodyweight moved by the athlete.'),
  ('no_load', 'No load', 'Use when tonnage should not be calculated from load.')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "muscle_roles" ("code", "name", "description")
VALUES
  ('primary', 'Primary', 'Main muscle or muscle node directly targeted by the exercise.'),
  ('secondary', 'Secondary', 'Muscle or muscle node meaningfully trained but not the primary target.'),
  ('stabilizer', 'Stabilizer', 'Muscle or muscle node mainly involved to support position, balance, bracing, or bar path.')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "patterns" ("code", "name", "description")
VALUES
  ('push', 'Push', 'Force production away from the body or into an implement through pressing, elbow extension, or upper-body projection.'),
  ('pull', 'Pull', 'Force production toward the body or against an implement through pulling, rowing, gripping, or upper-body traction.'),
  ('squat', 'Squat', 'Knee-dominant lower-body pattern built around knee flexion and extension with an upright or loaded torso.'),
  ('hinge', 'Hinge', 'Hip-dominant pattern built around hip flexion and extension, posterior-chain loading, and trunk bracing.'),
  ('carry', 'Carry', 'Loaded locomotion or positional holding where carrying capacity, grip, posture, and bracing are central.'),
  ('cyclical', 'Cyclical', 'Repeated locomotor or ergometer-style pattern where cyclic output and pacing dominate the effort.'),
  ('core', 'Core', 'Trunk bracing, anti-extension, anti-rotation, flexion, or force-transfer pattern.')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
WITH muscle_seed(code, name, common_name, description, chain) AS (
  VALUES
    ('upper_body', 'Upper body', 'Upper body', 'Upper-body muscle node used for broad hierarchy and filtering.', NULL),
    ('lower_body', 'Lower body', 'Lower body', 'Lower-body muscle node used for broad hierarchy and filtering.', NULL),
    ('neck', 'Neck', 'Neck', 'Neck and cervical control muscle node.', NULL),
    ('shoulders', 'Shoulders', 'Shoulders', 'Shoulder muscle node including delts, rotator cuff, and scapular contributors.', NULL),
    ('delts', 'Delts', 'Delts', 'Deltoid-focused muscle node.', NULL),
    ('rotator_cuff', 'Rotator cuff', 'Rotator cuff', 'Shoulder rotator cuff muscle node.', NULL),
    ('chest', 'Chest', 'Chest', 'Chest muscle node for pressing and pectoral work.', 'anterior'),
    ('pecs', 'Pecs', 'Pecs', 'Pectoralis-focused muscle node.', 'anterior'),
    ('back', 'Back', 'Back', 'Back muscle node including lats, traps, rhomboids, and lower back.', 'posterior'),
    ('trapezius', 'Trapezius', 'Traps', 'Trapezius muscle node.', 'posterior'),
    ('lower_back', 'Lower back', 'Lower back', 'Lumbar extension and spinal stability muscle node.', 'posterior'),
    ('spinal_stabilizers', 'Spinal stabilizers', 'Spinal stabilizers', 'Deep and segmental spinal stability muscle node.', NULL),
    ('arms', 'Arms', 'Arms', 'Arm muscle node including elbow flexors, elbow extensors, forearms, and grip.', NULL),
    ('biceps', 'Biceps', 'Biceps', 'Biceps-focused muscle node.', 'anterior'),
    ('triceps', 'Triceps', 'Triceps', 'Triceps-focused muscle node.', 'posterior'),
    ('forearms', 'Forearms', 'Forearms', 'Forearm flexion, extension, pronation, and supination muscle node.', NULL),
    ('grip', 'Grip', 'Grip', 'Grip and holding-capacity muscle node.', NULL),
    ('core', 'Core', 'Core', 'Trunk stability and bracing muscle node.', NULL),
    ('abs', 'Abs', 'Abs', 'Visible abdominal and trunk-flexion muscle node.', NULL),
    ('hips', 'Hips', 'Hips', 'Hip muscle node including glutes, adductors, abductors, hip flexors, and rotators.', NULL),
    ('glutes', 'Glutes', 'Glutes', 'Glute-focused muscle node.', 'posterior'),
    ('abductors', 'Abductors', 'Abductors', 'Hip abduction muscle node.', NULL),
    ('adductors', 'Adductors', 'Adductors', 'Hip adduction muscle node.', NULL),
    ('legs', 'Legs', 'Legs', 'Leg muscle node including thighs, hips, calves, and lower-leg support.', NULL),
    ('quads', 'Quads', 'Quads', 'Quadriceps-focused muscle node.', 'anterior'),
    ('hamstrings', 'Hamstrings', 'Hamstrings', 'Hamstring-focused muscle node.', 'posterior'),
    ('calves', 'Calves', 'Calves', 'Calf-focused muscle node.', 'posterior'),
    ('pectoralis_major_clavicular', 'Pectoralis major clavicular head', 'Upper pec', 'Upper portion of the pectoralis major.', 'anterior'),
    ('pectoralis_major_sternal', 'Pectoralis major sternal head', 'Mid pec', 'Middle portion of the pectoralis major.', 'anterior'),
    ('pectoralis_major_abdominal', 'Pectoralis major abdominal head', 'Lower pec', 'Lower portion of the pectoralis major.', 'anterior'),
    ('pectoralis_minor', 'Pectoralis minor', 'Pec minor', 'Deep pectoral muscle involved in scapular position and control.', 'anterior'),
    ('serratus_anterior', 'Serratus anterior', 'Serratus', 'Scapular protraction and upward rotation muscle visible along the ribs.', 'anterior'),
    ('latissimus_dorsi', 'Latissimus dorsi', 'Lats', 'Large back muscle involved in shoulder extension, adduction, and pulling.', 'posterior'),
    ('teres_major', 'Teres major', 'Teres major', 'Back muscle involved in shoulder extension and adduction.', 'posterior'),
    ('teres_minor', 'Teres minor', 'Teres minor', 'Rotator cuff muscle involved in shoulder external rotation.', 'posterior'),
    ('upper_trapezius', 'Upper trapezius', 'Upper traps', 'Upper trapezius fibers involved in scapular elevation and upward rotation.', 'posterior'),
    ('middle_trapezius', 'Middle trapezius', 'Middle traps', 'Middle trapezius fibers involved in scapular retraction.', 'posterior'),
    ('lower_trapezius', 'Lower trapezius', 'Lower traps', 'Lower trapezius fibers involved in scapular depression and upward rotation.', 'posterior'),
    ('rhomboids', 'Rhomboids', 'Rhomboids', 'Upper back muscles involved in scapular retraction and control.', 'posterior'),
    ('erector_spinae', 'Erector spinae', 'Spinal erectors', 'Spinal extensors involved in posture, hinging, and bracing.', 'posterior'),
    ('multifidus', 'Multifidus', 'Multifidus', 'Deep spinal stabilizer involved in segmental spinal control.', 'posterior'),
    ('quadratus_lumborum', 'Quadratus lumborum', 'QL', 'Deep lower-back muscle involved in lateral trunk stability.', NULL),
    ('deep_spinal_stabilizers', 'Deep spinal stabilizers', 'Deep spinal stabilizers', 'Deep trunk muscles involved in segmental spinal control.', NULL),
    ('anterior_deltoid', 'Anterior deltoid', 'Front delt', 'Front deltoid involved in shoulder flexion and pressing.', 'anterior'),
    ('lateral_deltoid', 'Lateral deltoid', 'Side delt', 'Side deltoid involved in shoulder abduction.', NULL),
    ('posterior_deltoid', 'Posterior deltoid', 'Rear delt', 'Rear deltoid involved in shoulder extension and horizontal abduction.', 'posterior'),
    ('supraspinatus', 'Supraspinatus', 'Supraspinatus', 'Rotator cuff muscle involved in shoulder abduction and humeral head control.', NULL),
    ('infraspinatus', 'Infraspinatus', 'Infraspinatus', 'Rotator cuff muscle involved in shoulder external rotation.', 'posterior'),
    ('subscapularis', 'Subscapularis', 'Subscapularis', 'Rotator cuff muscle involved in shoulder internal rotation.', 'anterior'),
    ('biceps_long_head', 'Biceps brachii long head', 'Biceps long head', 'Outer biceps head involved in elbow flexion and supination.', 'anterior'),
    ('biceps_short_head', 'Biceps brachii short head', 'Biceps short head', 'Inner biceps head involved in elbow flexion and supination.', 'anterior'),
    ('brachialis', 'Brachialis', 'Brachialis', 'Deep elbow flexor underneath the biceps.', 'anterior'),
    ('brachioradialis', 'Brachioradialis', 'Brachioradialis', 'Forearm muscle involved in elbow flexion.', NULL),
    ('triceps_long_head', 'Triceps brachii long head', 'Triceps long head', 'Long triceps head involved in elbow extension and shoulder extension.', 'posterior'),
    ('triceps_lateral_head', 'Triceps brachii lateral head', 'Triceps lateral head', 'Lateral triceps head involved in elbow extension.', 'posterior'),
    ('triceps_medial_head', 'Triceps brachii medial head', 'Triceps medial head', 'Medial triceps head involved in elbow extension.', 'posterior'),
    ('forearm_flexors', 'Forearm flexors', 'Forearm flexors', 'Forearm flexor group involved in wrist and finger flexion.', NULL),
    ('forearm_extensors', 'Forearm extensors', 'Forearm extensors', 'Forearm extensor group involved in wrist and finger extension.', NULL),
    ('forearm_pronators', 'Forearm pronators', 'Forearm pronators', 'Forearm muscles involved in pronation.', NULL),
    ('forearm_supinators', 'Forearm supinators', 'Forearm supinators', 'Forearm muscles involved in supination.', NULL),
    ('finger_flexors', 'Finger flexors', 'Finger flexors', 'Finger flexor group involved in gripping.', NULL),
    ('finger_extensors', 'Finger extensors', 'Finger extensors', 'Finger extensor group involved in hand opening and wrist balance.', NULL),
    ('intrinsic_hand_muscles', 'Intrinsic hand muscles', 'Intrinsic hand muscles', 'Small hand muscles involved in grip stability.', NULL),
    ('rectus_abdominis', 'Rectus abdominis', 'Abs', 'Visible abdominal muscle involved in trunk flexion and bracing.', 'anterior'),
    ('external_obliques', 'External obliques', 'External obliques', 'Outer oblique muscles involved in trunk rotation, side bending, and bracing.', 'anterior'),
    ('internal_obliques', 'Internal obliques', 'Internal obliques', 'Inner oblique muscles involved in trunk rotation, side bending, and bracing.', NULL),
    ('transverse_abdominis', 'Transverse abdominis', 'TVA', 'Deep abdominal muscle involved in abdominal pressure and trunk stability.', NULL),
    ('diaphragm', 'Diaphragm', 'Diaphragm', 'Primary breathing muscle involved in bracing and pressure control.', NULL),
    ('pelvic_floor', 'Pelvic floor', 'Pelvic floor', 'Deep pelvic stabilizer group involved in pressure and trunk control.', NULL),
    ('gluteus_maximus', 'Gluteus maximus', 'Glute max', 'Primary hip extensor and largest glute muscle.', 'posterior'),
    ('gluteus_medius', 'Gluteus medius', 'Glute med', 'Lateral hip muscle involved in abduction and pelvic stability.', NULL),
    ('gluteus_minimus', 'Gluteus minimus', 'Glute min', 'Deep lateral hip muscle involved in abduction and pelvic stability.', NULL),
    ('deep_hip_rotators', 'Deep hip rotators', 'Deep hip rotators', 'Deep hip muscles involved in hip rotation and stability.', NULL),
    ('tensor_fasciae_latae', 'Tensor fasciae latae', 'TFL', 'Anterior-lateral hip muscle involved in hip flexion, abduction, and internal rotation.', 'anterior'),
    ('rectus_femoris', 'Rectus femoris', 'Rectus femoris', 'Quadriceps head crossing the hip and knee.', 'anterior'),
    ('vastus_lateralis', 'Vastus lateralis', 'Vastus lateralis', 'Lateral quadriceps head contributing to thigh width.', 'anterior'),
    ('vastus_medialis', 'Vastus medialis', 'Vastus medialis', 'Medial quadriceps head near the knee.', 'anterior'),
    ('vastus_intermedius', 'Vastus intermedius', 'Vastus intermedius', 'Deep quadriceps head contributing to overall knee extension volume.', 'anterior'),
    ('biceps_femoris_long_head', 'Biceps femoris long head', 'Biceps femoris long head', 'Hamstring head involved in knee flexion and hip extension.', 'posterior'),
    ('biceps_femoris_short_head', 'Biceps femoris short head', 'Biceps femoris short head', 'Hamstring head involved primarily in knee flexion.', 'posterior'),
    ('semitendinosus', 'Semitendinosus', 'Semitendinosus', 'Medial hamstring involved in knee flexion and hip extension.', 'posterior'),
    ('semimembranosus', 'Semimembranosus', 'Semimembranosus', 'Medial hamstring involved in knee flexion and hip extension.', 'posterior'),
    ('adductor_magnus', 'Adductor magnus', 'Adductor magnus', 'Large adductor involved in hip adduction and hip extension.', NULL),
    ('adductor_longus', 'Adductor longus', 'Adductor longus', 'Adductor involved in hip adduction.', NULL),
    ('adductor_brevis', 'Adductor brevis', 'Adductor brevis', 'Adductor involved in hip adduction.', NULL),
    ('pectineus', 'Pectineus', 'Pectineus', 'Anterior adductor involved in hip adduction and flexion.', 'anterior'),
    ('gracilis', 'Gracilis', 'Gracilis', 'Long medial thigh muscle involved in hip adduction.', NULL),
    ('gastrocnemius_medial', 'Medial gastrocnemius', 'Medial gastroc', 'Medial head of the gastrocnemius.', 'posterior'),
    ('gastrocnemius_lateral', 'Lateral gastrocnemius', 'Lateral gastroc', 'Lateral head of the gastrocnemius.', 'posterior'),
    ('soleus', 'Soleus', 'Soleus', 'Deep calf muscle involved in plantar flexion.', 'posterior'),
    ('tibialis_anterior', 'Tibialis anterior', 'Tibialis anterior', 'Anterior lower-leg muscle involved in dorsiflexion.', 'anterior'),
    ('tibialis_posterior', 'Tibialis posterior', 'Tibialis posterior', 'Deep posterior lower-leg muscle involved in arch support.', 'posterior'),
    ('fibularis', 'Fibularis', 'Fibularis / peroneals', 'Lateral lower-leg muscle group involved in ankle eversion and stability.', NULL),
    ('neck_flexors', 'Neck flexors', 'Neck flexors', 'Anterior neck muscles involved in cervical flexion.', 'anterior'),
    ('neck_extensors', 'Neck extensors', 'Neck extensors', 'Posterior neck muscles involved in cervical extension.', 'posterior'),
    ('sternocleidomastoid', 'Sternocleidomastoid', 'SCM', 'Neck muscle involved in cervical rotation and flexion.', NULL),
    ('scalenes', 'Scalenes', 'Scalenes', 'Lateral neck muscles involved in posture and breathing.', NULL)
)
INSERT INTO "muscles" ("code", "name", "common_name", "description", "chain")
SELECT code, name, common_name, description, chain
FROM muscle_seed
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
WITH muscle_parent_mapping(child_code, parent_code) AS (
  VALUES
    ('neck', 'upper_body'),
    ('shoulders', 'upper_body'),
    ('chest', 'upper_body'),
    ('back', 'upper_body'),
    ('arms', 'upper_body'),
    ('core', 'upper_body'),
    ('hips', 'lower_body'),
    ('legs', 'lower_body'),
    ('delts', 'shoulders'),
    ('rotator_cuff', 'shoulders'),
    ('serratus_anterior', 'shoulders'),
    ('pecs', 'chest'),
    ('pectoralis_major_clavicular', 'pecs'),
    ('pectoralis_major_sternal', 'pecs'),
    ('pectoralis_major_abdominal', 'pecs'),
    ('pectoralis_minor', 'pecs'),
    ('latissimus_dorsi', 'back'),
    ('teres_major', 'back'),
    ('trapezius', 'back'),
    ('rhomboids', 'back'),
    ('lower_back', 'back'),
    ('spinal_stabilizers', 'lower_back'),
    ('teres_minor', 'rotator_cuff'),
    ('upper_trapezius', 'trapezius'),
    ('middle_trapezius', 'trapezius'),
    ('lower_trapezius', 'trapezius'),
    ('erector_spinae', 'lower_back'),
    ('multifidus', 'spinal_stabilizers'),
    ('quadratus_lumborum', 'lower_back'),
    ('deep_spinal_stabilizers', 'spinal_stabilizers'),
    ('anterior_deltoid', 'delts'),
    ('lateral_deltoid', 'delts'),
    ('posterior_deltoid', 'delts'),
    ('supraspinatus', 'rotator_cuff'),
    ('infraspinatus', 'rotator_cuff'),
    ('subscapularis', 'rotator_cuff'),
    ('biceps', 'arms'),
    ('triceps', 'arms'),
    ('forearms', 'arms'),
    ('biceps_long_head', 'biceps'),
    ('biceps_short_head', 'biceps'),
    ('brachialis', 'biceps'),
    ('brachioradialis', 'forearms'),
    ('triceps_long_head', 'triceps'),
    ('triceps_lateral_head', 'triceps'),
    ('triceps_medial_head', 'triceps'),
    ('grip', 'forearms'),
    ('forearm_flexors', 'forearms'),
    ('forearm_extensors', 'forearms'),
    ('forearm_pronators', 'forearms'),
    ('forearm_supinators', 'forearms'),
    ('finger_flexors', 'grip'),
    ('finger_extensors', 'forearms'),
    ('intrinsic_hand_muscles', 'grip'),
    ('abs', 'core'),
    ('rectus_abdominis', 'abs'),
    ('external_obliques', 'abs'),
    ('internal_obliques', 'abs'),
    ('transverse_abdominis', 'abs'),
    ('diaphragm', 'core'),
    ('pelvic_floor', 'core'),
    ('glutes', 'hips'),
    ('abductors', 'hips'),
    ('adductors', 'hips'),
    ('deep_hip_rotators', 'hips'),
    ('tensor_fasciae_latae', 'abductors'),
    ('gluteus_maximus', 'glutes'),
    ('gluteus_medius', 'abductors'),
    ('gluteus_minimus', 'abductors'),
    ('quads', 'legs'),
    ('hamstrings', 'legs'),
    ('calves', 'legs'),
    ('rectus_femoris', 'quads'),
    ('vastus_lateralis', 'quads'),
    ('vastus_medialis', 'quads'),
    ('vastus_intermedius', 'quads'),
    ('biceps_femoris_long_head', 'hamstrings'),
    ('biceps_femoris_short_head', 'hamstrings'),
    ('semitendinosus', 'hamstrings'),
    ('semimembranosus', 'hamstrings'),
    ('adductor_magnus', 'adductors'),
    ('adductor_longus', 'adductors'),
    ('adductor_brevis', 'adductors'),
    ('pectineus', 'adductors'),
    ('gracilis', 'adductors'),
    ('gastrocnemius_medial', 'calves'),
    ('gastrocnemius_lateral', 'calves'),
    ('soleus', 'calves'),
    ('tibialis_anterior', 'legs'),
    ('tibialis_posterior', 'legs'),
    ('fibularis', 'legs'),
    ('neck_flexors', 'neck'),
    ('neck_extensors', 'neck'),
    ('sternocleidomastoid', 'neck'),
    ('scalenes', 'neck')
)
UPDATE "muscles" child
SET "parent_muscle_id" = parent."id"
FROM muscle_parent_mapping
JOIN "muscles" parent ON parent."code" = muscle_parent_mapping.parent_code
WHERE child."code" = muscle_parent_mapping.child_code;
--> statement-breakpoint
WITH exercise_seed(code, title, loading_type_code, is_unilateral, pattern_code) AS (
  VALUES
    ('low_bar_squat', 'Low bar squat', 'external_load', false, 'squat'),
    ('mid_bar_squat', 'Mid bar squat', 'external_load', false, 'squat'),
    ('high_bar_squat', 'High bar squat', 'external_load', false, 'squat'),
    ('paused_squat', 'Paused squat', 'external_load', false, 'squat'),
    ('tempo_squat', 'Tempo squat', 'external_load', false, 'squat'),
    ('box_squat', 'Box squat', 'external_load', false, 'squat'),
    ('safety_bar_squat', 'Safety bar squat', 'external_load', false, 'squat'),
    ('front_squat', 'Front squat', 'external_load', false, 'squat'),
    ('hack_squat', 'Hack squat', 'external_load', false, 'squat'),
    ('leg_press', 'Leg press', 'external_load', false, 'squat'),
    ('bulgarian_split_squat', 'Bulgarian split squat', 'external_load', true, 'squat'),
    ('leg_extension', 'Leg extension', 'external_load', false, 'squat'),
    ('hip_abduction', 'Hip abduction', 'external_load', false, 'squat'),
    ('hip_adduction', 'Hip adduction', 'external_load', false, 'squat'),
    ('full_grip_bench_press', 'Full grip bench press', 'external_load', false, 'push'),
    ('natural_grip_bench_press', 'Natural grip bench press', 'external_load', false, 'push'),
    ('narrow_grip_bench_press', 'Narrow grip bench press', 'external_load', false, 'push'),
    ('paused_bench_press', 'Paused bench press', 'external_load', false, 'push'),
    ('close_grip_bench_press', 'Close grip bench press', 'external_load', false, 'push'),
    ('wide_grip_bench_press', 'Wide grip bench press', 'external_load', false, 'push'),
    ('spoto_press', 'Spoto press', 'external_load', false, 'push'),
    ('incline_barbell_bench_press', 'Incline barbell bench press', 'external_load', false, 'push'),
    ('dumbbell_bench_press', 'Dumbbell bench press', 'external_load', false, 'push'),
    ('machine_chest_press', 'Machine chest press', 'external_load', false, 'push'),
    ('cable_fly', 'Cable fly', 'external_load', false, 'push'),
    ('dumbbell_fly', 'Dumbbell fly', 'external_load', false, 'push'),
    ('pec_deck', 'Pec deck', 'external_load', false, 'push'),
    ('face_pull', 'Face pull', 'external_load', false, 'pull'),
    ('triceps_pushdown', 'Triceps pushdown', 'external_load', false, 'push'),
    ('rope_pushdown', 'Rope pushdown', 'external_load', false, 'push'),
    ('skull_crusher', 'Skull crusher', 'external_load', false, 'push'),
    ('conventional_deadlift', 'Conventional deadlift', 'external_load', false, 'hinge'),
    ('semi_sumo_deadlift', 'Semi-sumo deadlift', 'external_load', false, 'hinge'),
    ('sumo_deadlift', 'Sumo deadlift', 'external_load', false, 'hinge'),
    ('paused_deadlift', 'Paused deadlift', 'external_load', false, 'hinge'),
    ('deficit_deadlift', 'Deficit deadlift', 'external_load', false, 'hinge'),
    ('block_pull', 'Block pull', 'external_load', false, 'hinge'),
    ('rack_pull', 'Rack pull', 'external_load', false, 'hinge'),
    ('romanian_deadlift', 'Romanian deadlift', 'external_load', false, 'hinge'),
    ('trap_bar_deadlift', 'Trap bar deadlift', 'external_load', false, 'hinge'),
    ('good_morning', 'Good morning', 'external_load', false, 'hinge'),
    ('hip_thrust', 'Hip thrust', 'external_load', false, 'hinge'),
    ('back_extension', 'Back extension', 'bodyweight_plus_external', false, 'hinge'),
    ('seated_leg_curl', 'Seated leg curl', 'external_load', false, 'hinge'),
    ('lying_leg_curl', 'Lying leg curl', 'external_load', false, 'hinge'),
    ('pull_up', 'Pull-up', 'bodyweight', false, 'pull'),
    ('assisted_pull_up', 'Assisted pull-up', 'assisted_bodyweight', false, 'pull'),
    ('chin_up', 'Chin-up', 'bodyweight', false, 'pull'),
    ('lat_pulldown', 'Lat pulldown', 'external_load', false, 'pull'),
    ('barbell_row', 'Barbell row', 'external_load', false, 'pull'),
    ('dumbbell_row', 'Dumbbell row', 'external_load', true, 'pull'),
    ('seated_cable_row', 'Seated cable row', 'external_load', false, 'pull'),
    ('machine_row', 'Machine row', 'external_load', false, 'pull'),
    ('barbell_curl', 'Barbell curl', 'external_load', false, 'pull'),
    ('dumbbell_curl', 'Dumbbell curl', 'external_load', false, 'pull'),
    ('hammer_curl', 'Hammer curl', 'external_load', false, 'pull'),
    ('plank', 'Plank', 'no_load', false, 'core'),
    ('hanging_leg_raise', 'Hanging leg raise', 'bodyweight', false, 'core'),
    ('ab_wheel_rollout', 'Ab wheel rollout', 'bodyweight', false, 'core'),
    ('cable_crunch', 'Cable crunch', 'external_load', false, 'core'),
    ('farmer_carry', 'Farmer carry', 'external_load', false, 'carry'),
    ('standing_calf_raise', 'Standing calf raise', 'external_load', false, 'squat')
),
bodyweight_coefficients(exercise_code, coefficient) AS (
  VALUES
    ('assisted_pull_up', 1),
    ('back_extension', 0.5),
    ('chin_up', 1),
    ('pull_up', 1),
    ('hanging_leg_raise', 0.35),
    ('ab_wheel_rollout', 0.6)
)
INSERT INTO "exercises" (
  "code",
  "title",
  "loading_type_id",
  "pattern_id",
  "is_unilateral",
  "bodyweight_coefficient",
  "is_system",
  "publication_status"
)
SELECT
  exercise_seed.code,
  exercise_seed.title,
  loading_types."id",
  patterns."id",
  exercise_seed.is_unilateral,
  CASE
    WHEN exercise_seed.loading_type_code IN ('bodyweight', 'bodyweight_plus_external', 'assisted_bodyweight')
      THEN bodyweight_coefficients.coefficient
    WHEN exercise_seed.loading_type_code = 'no_load' THEN 0
    ELSE NULL
  END,
  true,
  'published'
FROM exercise_seed
JOIN "loading_types" ON loading_types."code" = exercise_seed.loading_type_code
JOIN "patterns" ON patterns."code" = exercise_seed.pattern_code
LEFT JOIN bodyweight_coefficients ON bodyweight_coefficients.exercise_code = exercise_seed.code
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
WITH relationship_seed(source_code, target_movement_code, role_code, default_transfer_coefficient) AS (
  VALUES
    ('low_bar_squat', 'squat', 'competition', 1),
    ('mid_bar_squat', 'squat', 'competition', 1),
    ('high_bar_squat', 'squat', 'competition', 1),
    ('high_bar_squat', 'deadlift', 'accessory', 0.3),
    ('paused_squat', 'squat', 'variant', 0.85),
    ('tempo_squat', 'squat', 'variant', 0.8),
    ('box_squat', 'squat', 'variant', 0.75),
    ('safety_bar_squat', 'squat', 'variant', 0.75),
    ('front_squat', 'squat', 'variant', 0.65),
    ('hack_squat', 'squat', 'accessory', 0.5),
    ('leg_press', 'squat', 'accessory', 0.45),
    ('bulgarian_split_squat', 'squat', 'accessory', 0.4),
    ('leg_extension', 'squat', 'accessory', 0.25),
    ('hip_abduction', 'squat', 'accessory', 0.2),
    ('hip_adduction', 'squat', 'accessory', 0.2),
    ('plank', 'squat', 'accessory', 0.2),
    ('ab_wheel_rollout', 'squat', 'accessory', 0.2),
    ('cable_crunch', 'squat', 'accessory', 0.15),
    ('standing_calf_raise', 'squat', 'accessory', 0.05),
    ('full_grip_bench_press', 'bench_press', 'competition', 1),
    ('natural_grip_bench_press', 'bench_press', 'competition', 1),
    ('narrow_grip_bench_press', 'bench_press', 'competition', 1),
    ('paused_bench_press', 'bench_press', 'variant', 0.9),
    ('close_grip_bench_press', 'bench_press', 'variant', 0.75),
    ('wide_grip_bench_press', 'bench_press', 'variant', 0.75),
    ('spoto_press', 'bench_press', 'variant', 0.8),
    ('incline_barbell_bench_press', 'bench_press', 'accessory', 0.55),
    ('dumbbell_bench_press', 'bench_press', 'accessory', 0.45),
    ('machine_chest_press', 'bench_press', 'accessory', 0.35),
    ('cable_fly', 'bench_press', 'accessory', 0.25),
    ('dumbbell_fly', 'bench_press', 'accessory', 0.25),
    ('pec_deck', 'bench_press', 'accessory', 0.2),
    ('face_pull', 'bench_press', 'accessory', 0.2),
    ('triceps_pushdown', 'bench_press', 'accessory', 0.25),
    ('rope_pushdown', 'bench_press', 'accessory', 0.2),
    ('skull_crusher', 'bench_press', 'accessory', 0.3),
    ('conventional_deadlift', 'deadlift', 'competition', 1),
    ('semi_sumo_deadlift', 'deadlift', 'competition', 1),
    ('sumo_deadlift', 'deadlift', 'competition', 1),
    ('paused_deadlift', 'deadlift', 'variant', 0.85),
    ('deficit_deadlift', 'deadlift', 'variant', 0.8),
    ('block_pull', 'deadlift', 'variant', 0.75),
    ('rack_pull', 'deadlift', 'variant', 0.65),
    ('romanian_deadlift', 'deadlift', 'accessory', 0.55),
    ('trap_bar_deadlift', 'deadlift', 'accessory', 0.65),
    ('good_morning', 'deadlift', 'accessory', 0.45),
    ('hip_thrust', 'deadlift', 'accessory', 0.35),
    ('back_extension', 'deadlift', 'accessory', 0.4),
    ('seated_leg_curl', 'deadlift', 'accessory', 0.25),
    ('lying_leg_curl', 'deadlift', 'accessory', 0.25),
    ('pull_up', 'deadlift', 'accessory', 0.25),
    ('assisted_pull_up', 'deadlift', 'accessory', 0.15),
    ('chin_up', 'deadlift', 'accessory', 0.2),
    ('lat_pulldown', 'deadlift', 'accessory', 0.25),
    ('barbell_row', 'deadlift', 'accessory', 0.35),
    ('dumbbell_row', 'deadlift', 'accessory', 0.25),
    ('seated_cable_row', 'deadlift', 'accessory', 0.25),
    ('machine_row', 'deadlift', 'accessory', 0.2),
    ('barbell_curl', 'deadlift', 'accessory', 0.1),
    ('dumbbell_curl', 'deadlift', 'accessory', 0.1),
    ('hammer_curl', 'deadlift', 'accessory', 0.1),
    ('farmer_carry', 'deadlift', 'accessory', 0.2),
    ('plank', 'deadlift', 'accessory', 0.2),
    ('ab_wheel_rollout', 'deadlift', 'accessory', 0.2),
    ('standing_calf_raise', 'deadlift', 'accessory', 0.05)
)
INSERT INTO "exercise_relationships" (
  "discipline_id",
  "source_exercise_id",
  "target_discipline_movement_id",
  "role_id",
  "default_transfer_coefficient"
)
SELECT
  disciplines."id",
  source_exercises."id",
  discipline_movements."id",
  exercise_roles."id",
  relationship_seed.default_transfer_coefficient
FROM relationship_seed
JOIN "disciplines" ON disciplines."code" = 'powerlifting'
JOIN "exercises" source_exercises ON source_exercises."code" = relationship_seed.source_code
JOIN "discipline_movements"
  ON discipline_movements."discipline_id" = disciplines."id"
  AND discipline_movements."code" = relationship_seed.target_movement_code
JOIN "exercise_roles" ON exercise_roles."code" = relationship_seed.role_code
ON CONFLICT ("discipline_id", "source_exercise_id", "target_discipline_movement_id") DO NOTHING;
--> statement-breakpoint
WITH exercise_muscle_seed(exercise_code, muscle_code, role_code, weight_percentage) AS (
  VALUES
    ('low_bar_squat', 'glutes', 'primary', 25),
    ('low_bar_squat', 'quads', 'primary', 21),
    ('low_bar_squat', 'lower_back', 'primary', 18),
    ('low_bar_squat', 'adductors', 'secondary', 12),
    ('low_bar_squat', 'hamstrings', 'secondary', 10),
    ('low_bar_squat', 'abs', 'stabilizer', 8),
    ('low_bar_squat', 'upper_trapezius', 'stabilizer', 6),
    ('mid_bar_squat', 'quads', 'primary', 26),
    ('mid_bar_squat', 'glutes', 'primary', 25),
    ('mid_bar_squat', 'lower_back', 'secondary', 14),
    ('mid_bar_squat', 'adductors', 'secondary', 13),
    ('mid_bar_squat', 'hamstrings', 'secondary', 8),
    ('mid_bar_squat', 'abs', 'stabilizer', 7),
    ('mid_bar_squat', 'upper_trapezius', 'stabilizer', 5),
    ('mid_bar_squat', 'calves', 'stabilizer', 2),
    ('high_bar_squat', 'quads', 'primary', 30),
    ('high_bar_squat', 'glutes', 'primary', 24),
    ('high_bar_squat', 'adductors', 'secondary', 14),
    ('high_bar_squat', 'lower_back', 'secondary', 10),
    ('high_bar_squat', 'abs', 'stabilizer', 8),
    ('high_bar_squat', 'hamstrings', 'stabilizer', 6),
    ('high_bar_squat', 'calves', 'stabilizer', 4),
    ('high_bar_squat', 'upper_trapezius', 'stabilizer', 4),
    ('paused_squat', 'quads', 'primary', 30),
    ('paused_squat', 'glutes', 'primary', 24),
    ('paused_squat', 'adductors', 'secondary', 15),
    ('paused_squat', 'lower_back', 'secondary', 11),
    ('paused_squat', 'abs', 'stabilizer', 8),
    ('paused_squat', 'hamstrings', 'stabilizer', 6),
    ('paused_squat', 'calves', 'stabilizer', 3),
    ('paused_squat', 'upper_trapezius', 'stabilizer', 3),
    ('tempo_squat', 'quads', 'primary', 30),
    ('tempo_squat', 'glutes', 'primary', 24),
    ('tempo_squat', 'adductors', 'secondary', 15),
    ('tempo_squat', 'lower_back', 'secondary', 11),
    ('tempo_squat', 'abs', 'stabilizer', 8),
    ('tempo_squat', 'hamstrings', 'stabilizer', 6),
    ('tempo_squat', 'calves', 'stabilizer', 3),
    ('tempo_squat', 'upper_trapezius', 'stabilizer', 3),
    ('box_squat', 'glutes', 'primary', 32),
    ('box_squat', 'hamstrings', 'primary', 25),
    ('box_squat', 'quads', 'secondary', 18),
    ('box_squat', 'lower_back', 'secondary', 12),
    ('box_squat', 'abs', 'stabilizer', 6),
    ('box_squat', 'adductors', 'stabilizer', 5),
    ('box_squat', 'upper_trapezius', 'stabilizer', 2),
    ('safety_bar_squat', 'quads', 'primary', 28),
    ('safety_bar_squat', 'trapezius', 'primary', 14),
    ('safety_bar_squat', 'rhomboids', 'primary', 8),
    ('safety_bar_squat', 'glutes', 'secondary', 18),
    ('safety_bar_squat', 'lower_back', 'secondary', 14),
    ('safety_bar_squat', 'abs', 'stabilizer', 8),
    ('safety_bar_squat', 'adductors', 'stabilizer', 5),
    ('safety_bar_squat', 'hamstrings', 'stabilizer', 5),
    ('front_squat', 'quads', 'primary', 35),
    ('front_squat', 'trapezius', 'primary', 15),
    ('front_squat', 'rhomboids', 'primary', 10),
    ('front_squat', 'abs', 'secondary', 14),
    ('front_squat', 'glutes', 'secondary', 12),
    ('front_squat', 'lower_back', 'stabilizer', 6),
    ('front_squat', 'adductors', 'stabilizer', 4),
    ('front_squat', 'hamstrings', 'stabilizer', 4),
    ('hack_squat', 'quads', 'primary', 55),
    ('hack_squat', 'glutes', 'secondary', 20),
    ('hack_squat', 'adductors', 'secondary', 10),
    ('hack_squat', 'hamstrings', 'stabilizer', 7),
    ('hack_squat', 'calves', 'stabilizer', 5),
    ('hack_squat', 'abs', 'stabilizer', 3),
    ('leg_press', 'quads', 'primary', 40),
    ('leg_press', 'glutes', 'primary', 30),
    ('leg_press', 'adductors', 'secondary', 12),
    ('leg_press', 'hamstrings', 'secondary', 8),
    ('leg_press', 'calves', 'stabilizer', 6),
    ('leg_press', 'abs', 'stabilizer', 4),
    ('bulgarian_split_squat', 'quads', 'primary', 35),
    ('bulgarian_split_squat', 'glutes', 'primary', 30),
    ('bulgarian_split_squat', 'adductors', 'secondary', 12),
    ('bulgarian_split_squat', 'hamstrings', 'secondary', 8),
    ('bulgarian_split_squat', 'abs', 'stabilizer', 7),
    ('bulgarian_split_squat', 'abductors', 'stabilizer', 5),
    ('bulgarian_split_squat', 'calves', 'stabilizer', 3),
    ('leg_extension', 'quads', 'primary', 100),
    ('hip_abduction', 'abductors', 'primary', 70),
    ('hip_abduction', 'glutes', 'secondary', 25),
    ('hip_abduction', 'abs', 'stabilizer', 5),
    ('hip_adduction', 'adductors', 'primary', 100),
    ('full_grip_bench_press', 'pecs', 'primary', 34.3),
    ('full_grip_bench_press', 'triceps', 'primary', 22.9),
    ('full_grip_bench_press', 'anterior_deltoid', 'secondary', 17.1),
    ('full_grip_bench_press', 'back', 'secondary', 11.4),
    ('full_grip_bench_press', 'rotator_cuff', 'stabilizer', 4.9),
    ('full_grip_bench_press', 'abs', 'stabilizer', 3.7),
    ('full_grip_bench_press', 'grip', 'stabilizer', 2.7),
    ('full_grip_bench_press', 'quads', 'stabilizer', 1.7),
    ('full_grip_bench_press', 'glutes', 'stabilizer', 0.9),
    ('full_grip_bench_press', 'calves', 'stabilizer', 0.4),
    ('natural_grip_bench_press', 'pecs', 'primary', 34.3),
    ('natural_grip_bench_press', 'triceps', 'primary', 22.9),
    ('natural_grip_bench_press', 'anterior_deltoid', 'secondary', 17.1),
    ('natural_grip_bench_press', 'back', 'secondary', 11.4),
    ('natural_grip_bench_press', 'rotator_cuff', 'stabilizer', 4.9),
    ('natural_grip_bench_press', 'abs', 'stabilizer', 3.7),
    ('natural_grip_bench_press', 'grip', 'stabilizer', 2.7),
    ('natural_grip_bench_press', 'quads', 'stabilizer', 1.7),
    ('natural_grip_bench_press', 'glutes', 'stabilizer', 0.9),
    ('natural_grip_bench_press', 'calves', 'stabilizer', 0.4),
    ('narrow_grip_bench_press', 'triceps', 'primary', 38),
    ('narrow_grip_bench_press', 'pecs', 'primary', 25),
    ('narrow_grip_bench_press', 'anterior_deltoid', 'secondary', 18),
    ('narrow_grip_bench_press', 'latissimus_dorsi', 'stabilizer', 7),
    ('narrow_grip_bench_press', 'rotator_cuff', 'stabilizer', 5),
    ('narrow_grip_bench_press', 'serratus_anterior', 'stabilizer', 3),
    ('narrow_grip_bench_press', 'abs', 'stabilizer', 2),
    ('narrow_grip_bench_press', 'grip', 'stabilizer', 2),
    ('paused_bench_press', 'pecs', 'primary', 36),
    ('paused_bench_press', 'triceps', 'primary', 24),
    ('paused_bench_press', 'anterior_deltoid', 'secondary', 18),
    ('paused_bench_press', 'latissimus_dorsi', 'stabilizer', 8),
    ('paused_bench_press', 'rotator_cuff', 'stabilizer', 5),
    ('paused_bench_press', 'serratus_anterior', 'stabilizer', 4),
    ('paused_bench_press', 'abs', 'stabilizer', 3),
    ('paused_bench_press', 'grip', 'stabilizer', 2),
    ('close_grip_bench_press', 'triceps', 'primary', 38),
    ('close_grip_bench_press', 'pecs', 'primary', 25),
    ('close_grip_bench_press', 'anterior_deltoid', 'secondary', 18),
    ('close_grip_bench_press', 'latissimus_dorsi', 'stabilizer', 7),
    ('close_grip_bench_press', 'rotator_cuff', 'stabilizer', 5),
    ('close_grip_bench_press', 'serratus_anterior', 'stabilizer', 3),
    ('close_grip_bench_press', 'abs', 'stabilizer', 2),
    ('close_grip_bench_press', 'grip', 'stabilizer', 2),
    ('wide_grip_bench_press', 'pecs', 'primary', 45),
    ('wide_grip_bench_press', 'triceps', 'secondary', 20),
    ('wide_grip_bench_press', 'anterior_deltoid', 'secondary', 15),
    ('wide_grip_bench_press', 'latissimus_dorsi', 'stabilizer', 8),
    ('wide_grip_bench_press', 'rotator_cuff', 'stabilizer', 5),
    ('wide_grip_bench_press', 'serratus_anterior', 'stabilizer', 4),
    ('wide_grip_bench_press', 'abs', 'stabilizer', 3),
    ('spoto_press', 'pecs', 'primary', 36),
    ('spoto_press', 'triceps', 'primary', 23),
    ('spoto_press', 'anterior_deltoid', 'secondary', 18),
    ('spoto_press', 'latissimus_dorsi', 'stabilizer', 8),
    ('spoto_press', 'rotator_cuff', 'stabilizer', 5),
    ('spoto_press', 'serratus_anterior', 'stabilizer', 4),
    ('spoto_press', 'abs', 'stabilizer', 4),
    ('spoto_press', 'grip', 'stabilizer', 2),
    ('incline_barbell_bench_press', 'pectoralis_major_clavicular', 'primary', 25),
    ('incline_barbell_bench_press', 'anterior_deltoid', 'primary', 23),
    ('incline_barbell_bench_press', 'pectoralis_major_sternal', 'primary', 14),
    ('incline_barbell_bench_press', 'pectoralis_major_abdominal', 'primary', 11),
    ('incline_barbell_bench_press', 'triceps', 'secondary', 20),
    ('incline_barbell_bench_press', 'serratus_anterior', 'stabilizer', 3),
    ('incline_barbell_bench_press', 'middle_trapezius', 'stabilizer', 2),
    ('incline_barbell_bench_press', 'rotator_cuff', 'stabilizer', 2),
    ('dumbbell_bench_press', 'pecs', 'primary', 38),
    ('dumbbell_bench_press', 'triceps', 'secondary', 20),
    ('dumbbell_bench_press', 'anterior_deltoid', 'secondary', 18),
    ('dumbbell_bench_press', 'rotator_cuff', 'stabilizer', 10),
    ('dumbbell_bench_press', 'serratus_anterior', 'stabilizer', 6),
    ('dumbbell_bench_press', 'middle_trapezius', 'stabilizer', 4),
    ('dumbbell_bench_press', 'abs', 'stabilizer', 4),
    ('machine_chest_press', 'pecs', 'primary', 45),
    ('machine_chest_press', 'triceps', 'secondary', 25),
    ('machine_chest_press', 'anterior_deltoid', 'secondary', 20),
    ('machine_chest_press', 'serratus_anterior', 'stabilizer', 5),
    ('machine_chest_press', 'middle_trapezius', 'stabilizer', 3),
    ('machine_chest_press', 'rotator_cuff', 'stabilizer', 2),
    ('cable_fly', 'pecs', 'primary', 70),
    ('cable_fly', 'anterior_deltoid', 'stabilizer', 10),
    ('cable_fly', 'serratus_anterior', 'stabilizer', 8),
    ('cable_fly', 'rotator_cuff', 'stabilizer', 6),
    ('cable_fly', 'middle_trapezius', 'stabilizer', 6),
    ('dumbbell_fly', 'pecs', 'primary', 65),
    ('dumbbell_fly', 'anterior_deltoid', 'stabilizer', 12),
    ('dumbbell_fly', 'rotator_cuff', 'stabilizer', 8),
    ('dumbbell_fly', 'serratus_anterior', 'stabilizer', 6),
    ('dumbbell_fly', 'middle_trapezius', 'stabilizer', 5),
    ('dumbbell_fly', 'abs', 'stabilizer', 4),
    ('pec_deck', 'pecs', 'primary', 75),
    ('pec_deck', 'anterior_deltoid', 'stabilizer', 10),
    ('pec_deck', 'serratus_anterior', 'stabilizer', 7),
    ('pec_deck', 'rotator_cuff', 'stabilizer', 4),
    ('pec_deck', 'middle_trapezius', 'stabilizer', 4),
    ('face_pull', 'posterior_deltoid', 'primary', 40),
    ('face_pull', 'back', 'primary', 35),
    ('face_pull', 'rotator_cuff', 'secondary', 25),
    ('triceps_pushdown', 'triceps', 'primary', 85),
    ('triceps_pushdown', 'forearms', 'stabilizer', 10),
    ('triceps_pushdown', 'abs', 'stabilizer', 5),
    ('rope_pushdown', 'triceps', 'primary', 85),
    ('rope_pushdown', 'forearms', 'stabilizer', 10),
    ('rope_pushdown', 'abs', 'stabilizer', 5),
    ('skull_crusher', 'triceps', 'primary', 75),
    ('skull_crusher', 'anterior_deltoid', 'stabilizer', 8),
    ('skull_crusher', 'forearms', 'stabilizer', 6),
    ('skull_crusher', 'pecs', 'stabilizer', 5),
    ('skull_crusher', 'rotator_cuff', 'stabilizer', 4),
    ('skull_crusher', 'abs', 'stabilizer', 2),
    ('conventional_deadlift', 'lower_back', 'primary', 22.9),
    ('conventional_deadlift', 'glutes', 'primary', 19),
    ('conventional_deadlift', 'hamstrings', 'primary', 15.2),
    ('conventional_deadlift', 'quads', 'secondary', 11.4),
    ('conventional_deadlift', 'latissimus_dorsi', 'secondary', 5),
    ('conventional_deadlift', 'trapezius', 'secondary', 4.5),
    ('conventional_deadlift', 'adductors', 'secondary', 7.6),
    ('conventional_deadlift', 'abs', 'stabilizer', 5.7),
    ('conventional_deadlift', 'grip', 'stabilizer', 4.8),
    ('conventional_deadlift', 'calves', 'stabilizer', 3.9),
    ('semi_sumo_deadlift', 'glutes', 'primary', 22),
    ('semi_sumo_deadlift', 'lower_back', 'primary', 18),
    ('semi_sumo_deadlift', 'adductors', 'primary', 15),
    ('semi_sumo_deadlift', 'hamstrings', 'secondary', 14),
    ('semi_sumo_deadlift', 'quads', 'secondary', 13),
    ('semi_sumo_deadlift', 'latissimus_dorsi', 'secondary', 4),
    ('semi_sumo_deadlift', 'trapezius', 'secondary', 3.5),
    ('semi_sumo_deadlift', 'abs', 'stabilizer', 4.5),
    ('semi_sumo_deadlift', 'grip', 'stabilizer', 4),
    ('semi_sumo_deadlift', 'calves', 'stabilizer', 2),
    ('sumo_deadlift', 'glutes', 'primary', 25),
    ('sumo_deadlift', 'adductors', 'primary', 22),
    ('sumo_deadlift', 'quads', 'primary', 18),
    ('sumo_deadlift', 'hamstrings', 'secondary', 10),
    ('sumo_deadlift', 'lower_back', 'secondary', 10),
    ('sumo_deadlift', 'latissimus_dorsi', 'secondary', 3.5),
    ('sumo_deadlift', 'trapezius', 'secondary', 2.5),
    ('sumo_deadlift', 'grip', 'stabilizer', 4),
    ('sumo_deadlift', 'abs', 'stabilizer', 3),
    ('sumo_deadlift', 'calves', 'stabilizer', 2),
    ('paused_deadlift', 'lower_back', 'primary', 25),
    ('paused_deadlift', 'glutes', 'primary', 18),
    ('paused_deadlift', 'hamstrings', 'primary', 16),
    ('paused_deadlift', 'quads', 'secondary', 13),
    ('paused_deadlift', 'latissimus_dorsi', 'secondary', 5.5),
    ('paused_deadlift', 'trapezius', 'secondary', 4.5),
    ('paused_deadlift', 'grip', 'stabilizer', 7),
    ('paused_deadlift', 'abs', 'stabilizer', 6),
    ('paused_deadlift', 'calves', 'stabilizer', 5),
    ('deficit_deadlift', 'quads', 'primary', 24),
    ('deficit_deadlift', 'lower_back', 'primary', 22),
    ('deficit_deadlift', 'glutes', 'primary', 18),
    ('deficit_deadlift', 'hamstrings', 'secondary', 14),
    ('deficit_deadlift', 'latissimus_dorsi', 'secondary', 4.5),
    ('deficit_deadlift', 'trapezius', 'secondary', 3.5),
    ('deficit_deadlift', 'grip', 'stabilizer', 7),
    ('deficit_deadlift', 'abs', 'stabilizer', 5),
    ('deficit_deadlift', 'calves', 'stabilizer', 2),
    ('block_pull', 'lower_back', 'primary', 28),
    ('block_pull', 'trapezius', 'primary', 14),
    ('block_pull', 'latissimus_dorsi', 'primary', 10),
    ('block_pull', 'glutes', 'primary', 16),
    ('block_pull', 'grip', 'secondary', 12),
    ('block_pull', 'hamstrings', 'secondary', 10),
    ('block_pull', 'abs', 'stabilizer', 6),
    ('block_pull', 'quads', 'stabilizer', 4),
    ('rack_pull', 'trapezius', 'primary', 18),
    ('rack_pull', 'latissimus_dorsi', 'primary', 12),
    ('rack_pull', 'lower_back', 'primary', 25),
    ('rack_pull', 'grip', 'primary', 18),
    ('rack_pull', 'hamstrings', 'secondary', 10),
    ('rack_pull', 'glutes', 'secondary', 9),
    ('rack_pull', 'abs', 'stabilizer', 5),
    ('rack_pull', 'quads', 'stabilizer', 3),
    ('romanian_deadlift', 'hamstrings', 'primary', 35),
    ('romanian_deadlift', 'glutes', 'primary', 25),
    ('romanian_deadlift', 'lower_back', 'secondary', 18),
    ('romanian_deadlift', 'grip', 'secondary', 8),
    ('romanian_deadlift', 'latissimus_dorsi', 'stabilizer', 6),
    ('romanian_deadlift', 'abs', 'stabilizer', 5),
    ('romanian_deadlift', 'calves', 'stabilizer', 3),
    ('trap_bar_deadlift', 'quads', 'primary', 28),
    ('trap_bar_deadlift', 'glutes', 'primary', 24),
    ('trap_bar_deadlift', 'hamstrings', 'secondary', 14),
    ('trap_bar_deadlift', 'lower_back', 'secondary', 12),
    ('trap_bar_deadlift', 'grip', 'secondary', 8),
    ('trap_bar_deadlift', 'latissimus_dorsi', 'stabilizer', 5),
    ('trap_bar_deadlift', 'abs', 'stabilizer', 5),
    ('trap_bar_deadlift', 'calves', 'stabilizer', 4),
    ('good_morning', 'lower_back', 'primary', 35),
    ('good_morning', 'hamstrings', 'primary', 30),
    ('good_morning', 'glutes', 'primary', 20),
    ('good_morning', 'abs', 'stabilizer', 8),
    ('good_morning', 'upper_trapezius', 'stabilizer', 4),
    ('good_morning', 'calves', 'stabilizer', 3),
    ('hip_thrust', 'glutes', 'primary', 70),
    ('hip_thrust', 'hamstrings', 'stabilizer', 12),
    ('hip_thrust', 'abs', 'stabilizer', 8),
    ('hip_thrust', 'quads', 'stabilizer', 6),
    ('hip_thrust', 'lower_back', 'stabilizer', 4),
    ('back_extension', 'lower_back', 'primary', 45),
    ('back_extension', 'glutes', 'primary', 30),
    ('back_extension', 'hamstrings', 'secondary', 15),
    ('back_extension', 'abs', 'stabilizer', 6),
    ('back_extension', 'latissimus_dorsi', 'stabilizer', 4),
    ('seated_leg_curl', 'hamstrings', 'primary', 85),
    ('seated_leg_curl', 'calves', 'stabilizer', 7),
    ('seated_leg_curl', 'glutes', 'stabilizer', 5),
    ('seated_leg_curl', 'abs', 'stabilizer', 3),
    ('lying_leg_curl', 'hamstrings', 'primary', 82),
    ('lying_leg_curl', 'calves', 'stabilizer', 6),
    ('lying_leg_curl', 'glutes', 'stabilizer', 5),
    ('lying_leg_curl', 'lower_back', 'stabilizer', 4),
    ('lying_leg_curl', 'abs', 'stabilizer', 3),
    ('pull_up', 'latissimus_dorsi', 'primary', 35),
    ('pull_up', 'teres_major', 'primary', 10),
    ('pull_up', 'rhomboids', 'primary', 8),
    ('pull_up', 'trapezius', 'primary', 7),
    ('pull_up', 'biceps', 'secondary', 15),
    ('pull_up', 'brachioradialis', 'secondary', 8),
    ('pull_up', 'abs', 'stabilizer', 6),
    ('pull_up', 'posterior_deltoid', 'stabilizer', 5),
    ('pull_up', 'grip', 'stabilizer', 6),
    ('assisted_pull_up', 'latissimus_dorsi', 'primary', 35),
    ('assisted_pull_up', 'teres_major', 'primary', 10),
    ('assisted_pull_up', 'rhomboids', 'primary', 8),
    ('assisted_pull_up', 'trapezius', 'primary', 7),
    ('assisted_pull_up', 'biceps', 'secondary', 15),
    ('assisted_pull_up', 'brachioradialis', 'secondary', 8),
    ('assisted_pull_up', 'abs', 'stabilizer', 6),
    ('assisted_pull_up', 'posterior_deltoid', 'stabilizer', 5),
    ('assisted_pull_up', 'grip', 'stabilizer', 6),
    ('chin_up', 'latissimus_dorsi', 'primary', 30),
    ('chin_up', 'biceps', 'primary', 25),
    ('chin_up', 'teres_major', 'secondary', 8),
    ('chin_up', 'rhomboids', 'secondary', 7),
    ('chin_up', 'trapezius', 'secondary', 5),
    ('chin_up', 'brachioradialis', 'secondary', 10),
    ('chin_up', 'abs', 'stabilizer', 6),
    ('chin_up', 'posterior_deltoid', 'stabilizer', 5),
    ('chin_up', 'grip', 'stabilizer', 4),
    ('lat_pulldown', 'latissimus_dorsi', 'primary', 35),
    ('lat_pulldown', 'teres_major', 'primary', 9),
    ('lat_pulldown', 'rhomboids', 'primary', 8),
    ('lat_pulldown', 'trapezius', 'primary', 8),
    ('lat_pulldown', 'biceps', 'secondary', 15),
    ('lat_pulldown', 'brachioradialis', 'secondary', 10),
    ('lat_pulldown', 'abs', 'stabilizer', 5),
    ('lat_pulldown', 'posterior_deltoid', 'stabilizer', 5),
    ('lat_pulldown', 'grip', 'stabilizer', 5),
    ('barbell_row', 'rhomboids', 'primary', 14),
    ('barbell_row', 'trapezius', 'primary', 14),
    ('barbell_row', 'teres_major', 'primary', 7),
    ('barbell_row', 'latissimus_dorsi', 'primary', 20),
    ('barbell_row', 'biceps', 'secondary', 12),
    ('barbell_row', 'lower_back', 'secondary', 12),
    ('barbell_row', 'grip', 'secondary', 8),
    ('barbell_row', 'abs', 'stabilizer', 7),
    ('barbell_row', 'hamstrings', 'stabilizer', 6),
    ('dumbbell_row', 'latissimus_dorsi', 'primary', 32),
    ('dumbbell_row', 'rhomboids', 'primary', 12),
    ('dumbbell_row', 'trapezius', 'primary', 10),
    ('dumbbell_row', 'teres_major', 'primary', 6),
    ('dumbbell_row', 'biceps', 'secondary', 14),
    ('dumbbell_row', 'forearms', 'secondary', 8),
    ('dumbbell_row', 'posterior_deltoid', 'stabilizer', 8),
    ('dumbbell_row', 'abs', 'stabilizer', 5),
    ('dumbbell_row', 'rotator_cuff', 'stabilizer', 5),
    ('seated_cable_row', 'rhomboids', 'primary', 16),
    ('seated_cable_row', 'trapezius', 'primary', 13),
    ('seated_cable_row', 'teres_major', 'primary', 6),
    ('seated_cable_row', 'latissimus_dorsi', 'primary', 25),
    ('seated_cable_row', 'biceps', 'secondary', 15),
    ('seated_cable_row', 'forearms', 'secondary', 8),
    ('seated_cable_row', 'posterior_deltoid', 'secondary', 7),
    ('seated_cable_row', 'abs', 'stabilizer', 5),
    ('seated_cable_row', 'lower_back', 'stabilizer', 5),
    ('machine_row', 'rhomboids', 'primary', 16),
    ('machine_row', 'trapezius', 'primary', 14),
    ('machine_row', 'teres_major', 'primary', 8),
    ('machine_row', 'latissimus_dorsi', 'primary', 25),
    ('machine_row', 'biceps', 'secondary', 14),
    ('machine_row', 'posterior_deltoid', 'secondary', 8),
    ('machine_row', 'forearms', 'secondary', 6),
    ('machine_row', 'abs', 'stabilizer', 5),
    ('machine_row', 'rotator_cuff', 'stabilizer', 4),
    ('barbell_curl', 'biceps', 'primary', 75),
    ('barbell_curl', 'forearm_flexors', 'stabilizer', 10),
    ('barbell_curl', 'brachioradialis', 'stabilizer', 8),
    ('barbell_curl', 'abs', 'stabilizer', 4),
    ('barbell_curl', 'anterior_deltoid', 'stabilizer', 3),
    ('dumbbell_curl', 'biceps', 'primary', 70),
    ('dumbbell_curl', 'forearm_flexors', 'stabilizer', 12),
    ('dumbbell_curl', 'brachioradialis', 'stabilizer', 10),
    ('dumbbell_curl', 'abs', 'stabilizer', 4),
    ('dumbbell_curl', 'anterior_deltoid', 'stabilizer', 4),
    ('hammer_curl', 'brachioradialis', 'primary', 40),
    ('hammer_curl', 'biceps', 'primary', 35),
    ('hammer_curl', 'forearm_flexors', 'secondary', 15),
    ('hammer_curl', 'forearm_extensors', 'secondary', 10),
    ('plank', 'abs', 'primary', 55),
    ('plank', 'spinal_stabilizers', 'secondary', 20),
    ('plank', 'glutes', 'stabilizer', 8),
    ('plank', 'quads', 'stabilizer', 7),
    ('plank', 'serratus_anterior', 'stabilizer', 5),
    ('plank', 'anterior_deltoid', 'stabilizer', 3),
    ('plank', 'calves', 'stabilizer', 2),
    ('hanging_leg_raise', 'abs', 'primary', 60),
    ('hanging_leg_raise', 'rectus_femoris', 'secondary', 15),
    ('hanging_leg_raise', 'tensor_fasciae_latae', 'secondary', 8),
    ('hanging_leg_raise', 'forearm_flexors', 'stabilizer', 7),
    ('hanging_leg_raise', 'grip', 'stabilizer', 5),
    ('hanging_leg_raise', 'latissimus_dorsi', 'stabilizer', 5),
    ('ab_wheel_rollout', 'abs', 'primary', 45),
    ('ab_wheel_rollout', 'latissimus_dorsi', 'secondary', 15),
    ('ab_wheel_rollout', 'triceps', 'secondary', 12),
    ('ab_wheel_rollout', 'serratus_anterior', 'secondary', 10),
    ('ab_wheel_rollout', 'spinal_stabilizers', 'stabilizer', 8),
    ('ab_wheel_rollout', 'glutes', 'stabilizer', 5),
    ('ab_wheel_rollout', 'anterior_deltoid', 'stabilizer', 5),
    ('cable_crunch', 'abs', 'primary', 75),
    ('cable_crunch', 'rectus_femoris', 'stabilizer', 8),
    ('cable_crunch', 'grip', 'stabilizer', 7),
    ('cable_crunch', 'lower_back', 'stabilizer', 5),
    ('cable_crunch', 'latissimus_dorsi', 'stabilizer', 5),
    ('farmer_carry', 'grip', 'primary', 35),
    ('farmer_carry', 'back', 'primary', 20),
    ('farmer_carry', 'forearm_flexors', 'secondary', 8),
    ('farmer_carry', 'forearm_extensors', 'secondary', 7),
    ('farmer_carry', 'abs', 'secondary', 10),
    ('farmer_carry', 'calves', 'secondary', 8),
    ('farmer_carry', 'glutes', 'stabilizer', 7),
    ('farmer_carry', 'quads', 'stabilizer', 5),
    ('standing_calf_raise', 'calves', 'primary', 100)
)
INSERT INTO "exercise_muscles" ("exercise_id", "muscle_id", "muscle_role_id", "weight_percentage")
SELECT exercises."id", muscles."id", muscle_roles."id", exercise_muscle_seed.weight_percentage
FROM exercise_muscle_seed
JOIN "exercises" ON exercises."code" = exercise_muscle_seed.exercise_code
JOIN "muscles" ON muscles."code" = exercise_muscle_seed.muscle_code
JOIN "muscle_roles" ON muscle_roles."code" = exercise_muscle_seed.role_code
ON CONFLICT ("exercise_id", "muscle_id") DO NOTHING;
--> statement-breakpoint
