name: Detect

outputs:
  ci-filters:
    description: Turbo filters
    value: ${{ steps.vars.outputs.filters }}
  ci-name:
    description: Workflow name
    value: ${{ steps.vars.outputs.name }}
  event-pr:
    description: Whether it is a pull request event
    value: ${{ steps.event.outputs.pr }}
  event-push:
    description: Whether it is a push event
    value: ${{ steps.event.outputs.push }}
  event-slug:
    description: Slugified branch name of the pull request
    value: ${{ steps.slug.outputs.value }}
  path-api:
    description: Whether API has been modified
    value: ${{ steps.paths.outputs.api }}
  path-manager:
    description: Whether Manager has been modified
    value: ${{ steps.paths.outputs.manager }}

runs:
  using: composite
  steps:
    - name: Modified paths
      uses: dorny/paths-filter@v3
      id: paths
      with:
        filters: |
          api:
            - 'apps/api/**'
          manager:
            - 'apps/manager/**'

    - name: CI variables
      shell: bash
      id: vars
      env:
        API: ${{ steps.paths.outputs.api }}
        MANAGER: ${{ steps.paths.outputs.manager }}
      run: |
        set -euo pipefail

        if [[ "$API" == 'true' && "$MANAGER" == 'true' ]]; then
          echo "filters=--filter=@powercoach/api --filter=@powercoach/manager" >> $GITHUB_OUTPUT
          echo "name=CI" >> $GITHUB_OUTPUT
        elif [[ "$API" == 'true' ]]; then
          echo "filters=--filter=@powercoach/api" >> $GITHUB_OUTPUT
          echo "name=API CI" >> $GITHUB_OUTPUT
        elif [[ "$MANAGER" == 'true' ]]; then
          echo "filters=--filter=@powercoach/manager" >> $GITHUB_OUTPUT
          echo "name=Manager CI" >> $GITHUB_OUTPUT
        fi

    - name: Github event
      id: event
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
      run: |
        set -euo pipefail

        echo "push=$([[ "$EVENT_NAME" == 'push' ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"
        echo "pr=$([[ "$EVENT_NAME" == 'pull_request' ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"

    - name: Branch slug
      if: ${{ steps.event.outputs.pr == 'true' }}
      id: slug
      shell: bash
      env:
        BRANCH: ${{ github.head_ref }}
      run: |
        set -euo pipefail

        slug="$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]')"
        slug="$(echo "$slug" | sed -E 's/[^a-z0-9]+/-/g')"
        slug="$(echo "$slug" | sed -E 's/^-*//')"
        slug="$(echo "$slug" | sed -E 's/-*$//')"

        echo "value=$slug" >> "$GITHUB_OUTPUT"