name: Rollback API
description: Rollback the API app to the last production deployed revision

inputs:
  main-sha:
    description: Github main branch SHA
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/core/summary
      with:
        title: Rollback API inputs
        data: '{ "Main SHA": "${{ inputs.main-sha }}" }'

    - name: Google auth
      uses: ./.github/actions/google/auth
      with:
        docker: 'false'

    - uses: ./.github/actions/google/find-all
      id: find
      with:
        branch-sha: ${{ inputs.main-sha }}
        search-images: 'false'

    - name: Production revision
      id: production
      shell: bash
      run: |
        name=$(
          gcloud run services describe "$GCP_SERVICE" \
            --region="$GCP_REGION" \
            --project="$GCP_PROJECT_ID" \
            --format="json(status.traffic)" \
          | jq -r '
            .status.traffic[]
            | select(.percent == 100)
            | .revisionName
          '
        )

        if -z "$name"; then
          echo "❌ Error: no production revision found"
          exit 1
        fi

        echo "ℹ️ Production revision found ⇒ $name"
        echo "name=$name" >> "$GITHUB_OUTPUT"

    - name: Rollback revision
      id: rollback
      shell: bash
      env:
        REVISION_NAMES: ${{ steps.find.outputs.revision-names-value }}
      run: |
        name=$(
          printf '%s' "$REVISION_NAMES" \
          | jq -r \
            --arg production_name "${{ steps.production.outputs.name }}" \
            '
              sort_by(.metadata.creationTimestamp)
              | reverse
              | map(.metadata.name) as $names
              | ($names | index($production_name)) as $production_index
              | if $production_index == null then empty else $names[$production_index + 1] // empty end
            '
        )

        if -z "$name"; then
          echo "⚠️ Warning: no rollback revision name found"
          exit 0
        fi

        echo "ℹ️ Rollback revision name found ⇒ $name"
        echo "name=$name" >> "$GITHUB_OUTPUT"

    - name: Traffic
      uses: ./.github/actions/google/traffic
      if: steps.rollback.outputs.name
      with:
        branch-sha: ${{ inputs.main-sha }}
        deploy-target: 'production'
        revision-name: ${{ steps.rollback.outputs.name }}

    - uses: ./.github/actions/core/summary
      with:
        title: Rollback API tasks
        data: |
          {
            "find.revision-names": "${{ steps.find.outputs.revision-names }}",
            "production.name": "${{ steps.production.outputs.name }}",
            "rollback.name": "${{ steps.rollback.outputs.name }}"
          }
