name: Google Cloud Run URL computation

inputs:
  branch-slug:
    description: Slugified branch name of the pull request
    required: false
  domain:
    description: Google Cloud Run domain
    required: true
  service:
    description: Service name
    required: true

outputs:
  value:
    description: Computed URL value
    value: ${{ steps.compute.outputs.value }}

runs:
  using: composite
  steps:
    - name: Google Cloud Run URL computation
      id: compute
      shell: bash
      run: |
        branch_slug=${{ inputs.branch-slug }}
        host="${{ inputs.service }}-${{ inputs.domain }}.a.run.app"

        [[ -n "$branch_slug" ]] && host="$branch_slug---$host"

        echo "value=https://$host/" >> "$GITHUB_OUTPUT"
