name: Manager CD
description: Powercoach continuous deployment. Deploys the Manager app to Vercel

inputs:
  branch-sha:
    description: Github branch SHA
    required: true
  deploy-target:
    description: Deploy target, "preview" (pull event) or "production" (push event)
    required: true
  manager-sha:
    description: SHA of the Manager source directory
    required: true
  pull-event:
    description: Whether it is a pull request event
    required: true
  pull-slug:
    description: Slugified linked issue found in the PR commit messages
    required: false
  push-event:
    description: Whether it is a push event
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/core/validate/deploy-target
      with:
        deploy-target: ${{ inputs.deploy-target }}

    - uses: ./.github/actions/core/validate/pull-slug
      with:
        deploy-target: ${{ inputs.deploy-target }}
        pull-slug: ${{ inputs.pull-slug }}

    - uses: ./.github/actions/core/summary
      with:
        title: Manager CD inputs
        data: |
          {
            "Branch SHA": "${{ inputs.branch-sha }}",
            "Manager SHA": "${{ inputs.manager-sha }}",
            "Pull event": "${{ inputs.pull-event }}",
            "Pull slug": "${{ inputs.pull-slug }}",
            "Push event": "${{ inputs.push-event }}"
          }

    - name: Host computation
      id: host
      shell: bash
      run: |
        host=$VCL_PROJECT-$VCL_TEAM.vercel.app

        if -n "${{ inputs.pull-slug }}"; then
          echo "value=${{ inputs.pull-slug }}-$host" >> "$GITHUB_OUTPUT"
        else
          echo "value=$host" >> "$GITHUB_OUTPUT"
        fi

    - name: URL computation
      id: url
      shell: bash
      run: echo "value=https://${{ steps.host.outputs.value }}" >> "$GITHUB_OUTPUT"

    - name: API URL computation
      id: api-url
      shell: bash
      run: |
        host=$GCP_SERVICE-$GCP_DOMAIN.a.run.app

        if -n "${{ inputs.pull-slug }}"; then
          echo "value=https://${{ inputs.pull-slug }}---$host" >> "$GITHUB_OUTPUT"
        else
          echo "value=https://$host" >> "$GITHUB_OUTPUT"
        fi

    - name: Find deployed host
      id: find
      uses: ./.github/actions/vercel/find-one
      with:
        branch-sha: ${{ inputs.branch-sha }}
        deploy-target: ${{ inputs.deploy-target }}
        manager-sha: ${{ inputs.manager-sha }}

    - name: Actions
      id: actions
      shell: bash
      run: |
        echo "build=${{ steps.find.outputs.found == 'false' }}" >> "$GITHUB_OUTPUT"
        echo "deploy=${{ steps.find.outputs.found == 'false' }}" >> "$GITHUB_OUTPUT"

        # Always assign host during pull events
        if -t "${{ inputs.pull-event }}"; then
          echo "assign=true" >> "$GITHUB_OUTPUT"
        fi

        # During push events, assign only if a host is found (production "rollback")
        if -t "${{ inputs.push-event }}"; then
          echo "assign=${{ steps.find.outputs.found == 'true' }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Build
      id: build
      if: steps.actions.outputs.build == 'true'
      shell: bash
      env:
        VITE_API_BASE_URL: ${{ steps.api-url.outputs.value }}
      run: |
        out_dir=apps/manager/dist

        echo "📦 Building Manager with..."
        echo "  -- Manager SHA ⇒ ${{ inputs.manager-sha }}"
        echo "  -- API URL ⇒ $VITE_API_BASE_URL"

        pnpm --filter=@powercoach/manager build
        sed -i "s/__MANAGER_SHA__/${{ inputs.manager-sha }}/g" "$out_dir/index.html"

        echo "out-dir=$out_dir" >> "$GITHUB_OUTPUT"

    - name: Deploy
      id: deploy
      if: steps.actions.outputs.deploy == 'true'
      uses: ./.github/actions/vercel/deploy
      with:
        branch-sha: ${{ inputs.branch-sha }}
        deploy-target: ${{ inputs.deploy-target }}
        manager-sha: ${{ inputs.manager-sha }}
        out-dir: ${{ steps.build.outputs.out-dir }}

    - name: Assign host
      id: assign-host
      if: steps.actions.outputs.assign == 'true'
      uses: ./.github/actions/vercel/assign
      with:
        check: ${{ steps.find.outputs.found }}
        host: ${{ steps.host.outputs.value }}
        id: ${{ steps.deploy.outputs.id || steps.find.outputs.id }}

    - uses: ./.github/actions/core/summary
      with:
        title: Manager CD tasks
        layout: 'list'
        level: '4'
        data: |
          {
            "api-url.value": "${{ steps.api-url.outputs.value }}",
            "find.found": "${{ steps.find.outputs.found }}",
            "find.id": "${{ steps.find.outputs.id }}",
            "actions.build": "${{ steps.actions.outputs.build }}",
            "actions.deploy": "${{ steps.actions.outputs.deploy }}",
            "actions.assign": "${{ steps.actions.outputs.assign }}",
            "build.out-dir": "${{ steps.build.outputs.out-dir }}",
            "deploy.id": "${{ steps.deploy.outputs.id }}",
            "assign-host.skipped": "${{ steps.assign-host.outputs.skipped }}"
          }
