name: Find rollback deployment
description: Retrieves rollback deployment from Vercel via the v6 API

inputs:
  token:
    description: Vercel token
    required: true

outputs:
  id:
    description: Deployment ID if found
    value: ${{ steps.find.outputs.id }}
  found:
    description: Whether the deployment has been found
    value: ${{ steps.find.outputs.found }}
  hash:
    description: Deployment hash metadata if found
    value: ${{ steps.find.outputs.hash }}
  host:
    description: Deployment host if found
    value: ${{ steps.find.outputs.host }}

runs:
  using: composite
  steps:
    - name: Find rollback deployment
      id: find
      shell: bash
      run: |
        echo "ðŸ” Querying Vercel rollback deployment"

        response=$(
          curl \
            --header "Authorization: Bearer ${{ inputs.token }}" \
            --fail \
            --silent \
            --url "https://api.vercel.com/v6/deployments?target=production&limit=2" \
          2>/dev/null \
          | jq -r "{
              id: .deployments[1].uid,
              hash: .deployments[1].meta.hash,
              host: .deployments[1].url,
            } // empty" \
          || echo ""
        )

        if [[ -n "$response" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
          echo "id=$(echo "$response" | jq -r '.id')" >> "$GITHUB_OUTPUT"
          echo "hash=$(echo "$response" | jq -r '.hash')" >> "$GITHUB_OUTPUT"
          echo "host=$(echo "$response" | jq -r '.host')" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
