name: Revision state
description: Retrieves a Google Cloud Run revision state using the given hash

inputs:
  artifacts-repository:
    description: Artifact repository
    required: true
  hash:
    description: Unique hash identifier
    required: true
  project-id:
    description: Project ID
    required: true
  region:
    description: Region name
    required: true
  service:
    description: Service name
    required: true

outputs:
  active:
    description: Whether the revision is active
    value: ${{ steps.state.outputs.active }}
  revision:
    description: The Google Cloud Run revision matching the found version
    value: ${{ steps.state.outputs.revision }}
  traffic:
    description: Whether the revision is receiving traffic
    value: ${{ steps.state.outputs.traffic }}
  version:
    description: The Artifactory Registry version matching the given hash
    value: ${{ steps.state.outputs.version }}

runs:
  using: composite
  steps:
    - name: Revision state
      id: state
      shell: bash
      run: |
        artifacts_repository="${{ inputs.artifacts-repository }}"
        tag="${{ inputs.hash }}"
        project_id="${{ inputs.project-id }}"
        region="${{ inputs.region }}"
        service="${{ inputs.service }}"

        echo "active=false" >> "$GITHUB_OUTPUT"
        echo "traffic=false" >> "$GITHUB_OUTPUT"

        echo "🔍 Looking for an artifact version with"
        echo "     -- Tag ⇒ ${tag}"

        tags=$(
          gcloud artifacts docker tags list "${artifacts_repository}" \
            --format=json \
            --filter="tag:${tag}" 2>/dev/null
        )

        version=$(
          jq -r '.[0].version // empty' <<< "$tags" 2>/dev/null
        )

        if [[ -z "$version" ]]; then
          echo "❌ No versions found"
          echo "version=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "✅ Found version ⇒ ...${version: -32}"
        echo "version=$version" >> "$GITHUB_OUTPUT"

        digest=${version##*/versions/}
        image="${artifacts_repository}@${digest}"

        echo "🔍 Looking for a revision with"
        echo "     -- Image ⇒ ...${image: -32}"

        revisions=$(
          gcloud run revisions list \
            --region="${region}" \
            --project="${project_id}" \
            --service="${service}" \
            --format=json 2>/dev/null
        )

        revision=$(
          jq -r --arg image "$image" '
            .[]
            | select(.spec.containers[0].image == $image)
            | .metadata.name
            // empty
          ' <<< "$revisions"
        )

        if [[ -z "$revision" ]]; then
          echo "❌ No revisions found"
          echo "revision=" >> "$GITHUB_OUTPUT"
          exit 0
        elif [[ "$revision" == *$'\n'* ]]; then
          echo "❌ Multiple revisions found"
          echo "revision=" >> "$GITHUB_OUTPUT"
          while IFS= read -r line; do
            printf '     ⇒ %s\n' "$line"
          done <<< "$revision"
          exit 0
        fi

        echo "✅ Found revision ⇒ ${revision}"
        echo "revision=$revision" >> "$GITHUB_OUTPUT"

        echo "🔍 Looking for the revision running state with"
        echo "     -- Revision ⇒ ${revision}"

        services=$(
          gcloud run services describe "${service}" \
            --region="${region}" \
            --project="${project_id}" \
            --format=json 2>/dev/null
        )

        traffic=$(
          jq -r --arg revision "${revision}" '
            .status.traffic[]
            | select(.revisionName == $revision)
            | { percent: (.percent // 0) }
            // empty
            ' <<< "$services" 2>/dev/null
        )

        if [[ -z "$traffic" ]]; then
          echo "🛑 Revision $revision is not active"
          echo "active=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "🟢 Revision $revision is active"
        echo "active=true" >> "$GITHUB_OUTPUT"

        percent=$(
          jq -r '.percent // empty' <<< "$traffic" 2>/dev/null
        )

        if [[ "$percent" != 0 ]]; then
          echo "🚀 Revision $revision is receiving traffic"
          echo "traffic=true" >> "$GITHUB_OUTPUT"
        else
          echo "😴 Revision $revision is not receiving any traffic"
          echo "traffic=false" >> "$GITHUB_OUTPUT"
        fi
