name: State
description: Retrieves a Google Cloud Run state using the given hash

inputs:
  artifacts-repository:
    description: Artifact repository
    required: true
  hash:
    description: Unique hash identifier
    required: true
  project-id:
    description: Project ID
    required: true
  region:
    description: Region name
    required: true
  service:
    description: Service name
    required: true

outputs:
  revision:
    description: The Google Cloud Run revision
    value: ${{ steps.state.outputs.name }}
  version:
    description: The Google Cloud version (digest) of the Docker image
    value: ${{ steps.state.outputs.version }}

runs:
  using: composite
  steps:
    - name: State
      id: state
      shell: bash
      run: |
        artifacts_repository="${{ inputs.artifacts-repository }}"
        tag="${{ inputs.hash }}"
        project_id="${{ inputs.project-id }}"
        region="${{ inputs.region }}"
        service="${{ inputs.service }}"

        echo "🔍 Looking for an artifact version with"
        echo "     -- Tag ⇒ $tag"

        version=$(
          gcloud artifacts docker tags list "${artifacts_repository}" \
            --format="value(version)" \
            --filter="tag=$tag"
        )

        if [[ -z "$version" ]]; then
          echo "❌ No versions found"
          echo "version=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "✅ Found version ⇒ ...${version: -32}"
        echo "version=$version" >> "$GITHUB_OUTPUT"

        digest=${version##*/versions/}
        image="${artifacts_repository}@${digest}"

        echo "🔍 Looking for a revision with"
        echo "     -- Image ⇒ ...${image: -32}"

        revision=$(
          gcloud run revisions list \
            --region="${region}" \
            --project="${project_id}" \
            --service="${service}" \
            --filter="spec.containers[].image=$image" \
            --format=json 2>/dev/null
        )

        if [[ -z "$revision" ]]; then
          echo "❌ No revisions found"
          echo "revision=" >> "$GITHUB_OUTPUT"
          exit 0
        elif [[ "$revision" == *$'\n'* ]]; then
          echo "❌ Multiple revisions found"
          echo "revision=" >> "$GITHUB_OUTPUT"
          while IFS= read -r line; do
            printf '     ⇒ %s\n' "$line"
          done <<< "$revision"
          exit 0
        fi

        echo "✅ Found revision ⇒ ${revision}"
        echo "revision=$revision" >> "$GITHUB_OUTPUT"
