name: Powercoach Summary
description: Generate a Markdown summary table in GITHUB_STEP_SUMMARY from a JSON key/value mapping

inputs:
  data:
    description: JSON object of key/value pairs to include in the summary
    required: true
  level:
    description: Markdown heading level (1–6)
    required: false
    default: '2'
  title:
    description: Title of the summary section
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        {
          echo "$(printf %${{ inputs.level }}s | tr ' ' '#') ${{ inputs.title }}"
          echo ""
          echo "| Name | Value |"
          echo "| --- | --- |"

          # Itère sur chaque paire clé/valeur
          jq -r 'to_entries[] | "\(.key)|\(.value)"' <<< '${{ inputs.data }}' \
          | while IFS="|" read -r key value; do
              # "true"/"false" → emoji
              if [[ "$value" == "true" ]]; then
                value="✅"
              elif [[ "$value" == "false" ]]; then
                value="❌"
              fi

              echo "| $key | ${value:-❌} |"
            done

          echo ""
        } >> "$GITHUB_STEP_SUMMARY"
