name: Powercoach Summary
description: Generate a Markdown summary table in GITHUB_STEP_SUMMARY from a JSON key/value mapping

inputs:
  data:
    description: JSON object of key/value pairs to include in the summary
    required: true
  layout:
    description: Defines the way the summary is displayed. Values are "table" or "list"
    required: false
    default: 'table'
  level:
    description: Markdown heading level (1–6)
    required: false
    default: '2'
  title:
    description: Title of the summary section
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        DATA: ${{ inputs.data }}
        LAYOUT: ${{ inputs.layout }}
        LEVEL: ${{ inputs.level }}
        TITLE: ${{ inputs.title }}
      with:
        script: |
          const fs = require('fs');
          const { DATA, LAYOUT, LEVEL, TITLE, GITHUB_STEP_SUMMARY } = process.env;
          const isTable = LAYOUT === 'table';
          const data = JSON.parse(DATA.replace(/:\s*"([^"]*)"/gs, (_, value) => {
            return `: "${value.replace(/\n/g, '\\n')}"`;
          }))

          let output = '#'.repeat(parseInt(LEVEL)) + ' ' + TITLE + '\n\n';

          if (isTable) {
            output += '| Name | Value |\n| --- | --- |\n';
          }

          Object.entries(data).forEach(([key, value]) => {
            const displayedValue = value === true ? '✅' : !value ? '❌' : `${value}`.replace(/\n/g, '<br>');
            output += isTable
              ? `| ${key} | ${displayedValue} |\n`
              : `- ${key} ⇒ ${displayedValue}\n`;
          });

          output += '\n';
          fs.appendFileSync(GITHUB_STEP_SUMMARY, output);
