name: API CD

inputs:
  artifacts-repository:
    description: Google Cloud Platform Artifact Registry
    required: true
  override-tag:
    description: Force a tagged revision to be rebuilt and deployed
    required: false
    default: 'false'
  project-id:
    description: Google Cloud Platform Project ID
    required: true
  region:
    description: Google Cloud Platform Region name
    required: true
  service:
    description: Google Cloud Platform Service name
    required: true
  service-account:
    description: Google Cloud Platform Service Account name
    required: true
  tag:
    description: Google Cloud Platform revision tag name
    required: false
  wif-provider:
    description: Google Cloud Platform Workload Identity Federation provider path
    required: true

outputs:
  url:
    description: Running API URL
    value: ${{ steps.revision.outputs.url || steps.deploy.outputs.url }}

runs:
  using: composite
  steps:
    - name: Docker image name
      id: image
      shell: bash
      run: |
        echo "name=${{ inputs.region }}-docker.pkg.dev/${{ inputs.project-id }}/${{ inputs.artifacts-repository }}/${{ inputs.service }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.wif-provider }}
        service_account: ${{ inputs.service-account }}
        token_format: 'access_token'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      shell: bash
      run: |
        gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet

    - name: Revision detection
      if: ${{ inputs.override-tag == 'false' && inputs.tag != '' }}
      id: revision
      shell: bash
      run: |
        url="$(gcloud run revisions list \
          --service="${{ inputs.service }}" \
          --region="${{ inputs.region }}" \
          --filter="metadata.annotations.\"run.googleapis.com/tags\"~(^|,)${{ inputs.tag }}(,|$)" \
          --format="value(status.url)")"
        
        echo "detected=$([[ "$url" != '' ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"
        echo "url=$url" >> "$GITHUB_OUTPUT"

    - name: Build image
      if: ${{ steps.revision.outputs.detected != 'true' }}
      shell: bash
      run: |
        docker build \
          -f apps/api/Dockerfile \
          -t "${{ steps.image.outputs.name }}" \
          .

    - name: Push image
      if: ${{ steps.revision.outputs.detected != 'true' }}
      shell: bash
      run: docker push "${{ steps.image.outputs.name }}"

    - name: Deploy to Cloud Run
      if: ${{ steps.revision.outputs.detected != 'true' }}
      id: deploy
      shell: bash
      run: |
        set -euo pipefail
        
        flags=(
          "--allow-unauthenticated"
          "--cpu=1"
          "--image=\"${{ steps.image.outputs.name }}\""
          "--liveness-probe httpGet.path=/v1/health"
          "--max-instances=10"
          "--memory=512Mi"
          "--platform=managed"
          "--port=8080"
          "--project=\"${{ inputs.project-id }}\""
          "--region=\"${{ inputs.region }}\""
          "--set-env-vars=\"HOST=0.0.0.0\""
          "--set-env-vars=\"LOG_LEVEL=info\""
          "--set-env-vars=\"NODE_ENV=production\""
          "--startup-probe httpGet.path=/v1/health,initialDelaySeconds=5,periodSeconds=2,timeoutSeconds=1,failureThreshold=5"
        )
        
        if ${{ inputs.tag != '' }}; then
          flags+=("--no-traffic")
          flags+=("--tag=\"${{ inputs.tag }}\"")
        fi
        
        url=$(gcloud run deploy "${{ inputs.service }}" "${flags[@]}" --quiet --format="value(status.url)")
        echo "url=$url" >> "$GITHUB_OUTPUT"