name: Powercoach context
description: Describes the context of the main Powercoach workflow

outputs:
  api-sha:
    description: SHA of the API source directory
    value: ${{ steps.sha.outputs.api }}
  branch-sha:
    description: Github branch SHA
    value: ${{ steps.sha.outputs.branch }}
  cd-action:
    description: Whether CD should be ran
    value: ${{ steps.cd.outputs.action }}
  ci-action:
    description: Whether CI should be ran
    value: ${{ steps.ci.outputs.action }}
  close-event:
    description: Whether it is a closed pull request event (no merge)
    value: ${{ steps.event.outputs.close }}
  commit-branch-sha:
    description: Github branch SHA found in the last commit message
    value: ${{ steps.commit.outputs.branch-sha }}
  commit-pull-slug:
    description: Slugified Github PR branch name found in the last commit message
    value: ${{ steps.commit.outputs.pull-slug }}
  deploy-target:
    description: Deploy target, "preview" (pull event) or "production" (push event)
    value: ${{ steps.deploy.outputs.target }}
  manager-sha:
    description: SHA of the Manager source directory
    value: ${{ steps.sha.outputs.manager }}
  prune-action:
    description: Whether prune should be ran
    value: ${{ steps.prune.outputs.action }}
  pull-event:
    description: Whether it is a pull request event
    value: ${{ steps.event.outputs.pull }}
  pull-slug:
    description: Slugified Github PR branch name
    value: ${{ steps.pull.outputs.slug }}
  push-event:
    description: Whether it is a push event
    value: ${{ steps.event.outputs.push }}
  turbo-filter:
    description: Turbo filter command line flag
    value: ${{ steps.turbo.outputs.filter }}

runs:
  using: composite
  steps:
    - name: Modified paths
      uses: dorny/paths-filter@v3
      id: paths
      with:
        filters: |
          {
            "api": ["apps/api/**"],
            "manager": ["apps/manager/**"]
          }

    - name: Github event
      id: event
      shell: bash
      run: |
        if -e "${{ github.event_name }}" "push"; then
          echo "push=true" >> "$GITHUB_OUTPUT"
          echo "pull=false" >> "$GITHUB_OUTPUT"
        fi

        if -e "${{ github.event_name }}" "pull_request"; then
          echo "push=false" >> "$GITHUB_OUTPUT"
          echo "pull=true" >> "$GITHUB_OUTPUT"
        fi

        if -e "${{ github.event_name }}" "pull_request" &&
           -e "${{ github.event.action }}" "closed"; then
          echo "close=true" >> "$GITHUB_OUTPUT"
        else
          echo "close=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Deploy target
      id: deploy
      shell: bash
      run: |
        if -t "${{ steps.event.outputs.push }}"; then
          echo "target=production" >> "$GITHUB_OUTPUT"
        fi

        if -t "${{ steps.event.outputs.pull }}"; then
          echo "target=preview" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit data
      id: commit
      if: steps.event.outputs.push == 'true'
      shell: bash
      run: |
        branch=$(
          echo "${{ github.event.head_commit.message }}" \
          | sed -nE 's#^From[[:space:]]+((feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)/[a-z]+/[A-Za-z0-9_-]+)$#\1#p'
        )

        if -n "$branch"; then
          echo "branch-sha=$(sumify "$branch")" >> "$GITHUB_OUTPUT"
          echo "pull-slug=$(slugify "$branch")" >> "$GITHUB_OUTPUT"
        fi

    - name: Pull Github event slug
      id: pull
      if: steps.event.outputs.pull == 'true'
      shell: bash
      run: echo "slug=$(slugify "${{ github.head_ref }}")" >> "$GITHUB_OUTPUT"

    - name: Turbo
      shell: bash
      id: turbo
      run: |
        filter=""

        if -t "${{ steps.paths.outputs.api }}"; then
          filter+=" --filter=@powercoach/api"
        fi

        if -t "${{ steps.paths.outputs.manager }}"; then
          filter+=" --filter=@powercoach/manager"
        fi

        echo "filter=$filter" >> "$GITHUB_OUTPUT"

    - name: CI
      shell: bash
      id: ci
      run: |
        action="false"

        if -t "${{ steps.event.outputs.push }}" &&
           -n "${{ steps.turbo.outputs.filter }}"; then
          action="true"
        fi

        if -t "${{ steps.event.outputs.pull }}" &&
           -e "${{ github.event.pull_request.head.repo.full_name }}" "${{ github.repository }}" &&
           -n "${{ steps.turbo.outputs.filter }}"; then
          action="true"
        fi

        if -t "${{ steps.event.outputs.close }}"; then
          action="false"
        fi

        echo "action=$action" >> "$GITHUB_OUTPUT"

    - name: CD
      id: cd
      shell: bash
      run: echo "action=${{ steps.ci.outputs.action }}" >> "$GITHUB_OUTPUT"

    - name: Cutted sha256sum
      id: sha
      shell: bash
      run: |
        echo "api=$(sumify --dir apps/api)" >> "$GITHUB_OUTPUT"
        echo "manager=$(sumify --dir apps/manager)" >> "$GITHUB_OUTPUT"

        if -t "${{ steps.event.outputs.pull }}"; then
          echo "branch=$(sumify "${{ github.head_ref }}")" >> "$GITHUB_OUTPUT"
        fi

        if -t "${{ steps.event.outputs.push }}"; then
          echo "branch=$(sumify "${{ github.ref_name }}")" >> "$GITHUB_OUTPUT"
        fi

    - name: Prune
      id: prune
      shell: bash
      run: |
        action="false"

        if -t "${{ steps.event.outputs.close }}" && 
           -f "${{ github.event.pull_request.merged }}"; then
          action="true"
        fi

        if -t "${{ steps.event.outputs.push }}"; then
          action="true"
        fi

        echo "action=$action" >> "$GITHUB_OUTPUT"

    - uses: ./.github/actions/core/summary
      with:
        title: Context outputs
        data: |
          {
            "API SHA": "${{ steps.sha.outputs.api }}",
            "Branch SHA": "${{ steps.sha.outputs.branch }}",
            "CD action": "${{ steps.cd.outputs.action }}",
            "CI action": "${{ steps.ci.outputs.action }}",
            "Close event": "${{ steps.event.outputs.close }}",
            "Commit branch SHA": "${{ steps.commit.outputs.branch-sha }}",
            "Commit pull slug": "${{ steps.commit.outputs.pull-slug }}",
            "Deploy target": "${{ steps.deploy.outputs.target }}",
            "Manager SHA": "${{ steps.sha.outputs.manager }}",
            "Prune action": "${{ steps.prune.outputs.action }}",
            "Pull event": "${{ steps.event.outputs.pull }}",
            "Pull slug": "${{ steps.pull.outputs.slug }}",
            "Push event": "${{ steps.event.outputs.push }}",
            "Turbo filter": "${{ steps.turbo.outputs.filter }}"
          }

    - uses: ./.github/actions/core/summary
      with:
        title: Context tasks
        layout: 'list'
        level: '4'
        data: |
          {
            "API path": "${{ steps.paths.outputs.api }}",
            "Manager path": "${{ steps.paths.outputs.manager }}"
          }
