name: Powercoach context
description: Describes the context of the main Powercoach workflow

outputs:
  api-sha:
    description: SHA of the API source directory
    value: ${{ steps.sha.outputs.api }}
  branch-sha:
    description: Github branch SHA
    value: ${{ steps.sha.outputs.branch }}
  ci-action:
    description: Whether CI should be ran
    value: ${{ steps.ci.outputs.action }}
  cd-action:
    description: Whether CD should be ran
    value: ${{ steps.cd.outputs.action }}
  deploy-target:
    description: Deploy target, "preview" (pull event) or "production" (push event)
    value: ${{ steps.deploy.outputs.target }}
  manager-sha:
    description: SHA of the Manager source directory
    value: ${{ steps.sha.outputs.manager }}
  pull-event:
    description: Whether it is a pull request event
    value: ${{ steps.event.outputs.pull }}
  pull-slug:
    description: Slugified linked issue found in the PR commit messages
    value: ${{ steps.pull.outputs.slug }}
  push-event:
    description: Whether it is a push event
    value: ${{ steps.event.outputs.push }}
  turbo-filter:
    description: Turbo filter command line flag
    value: ${{ steps.turbo.outputs.filter }}

runs:
  using: composite
  steps:
    - name: Modified paths
      uses: dorny/paths-filter@v3
      id: paths
      with:
        filters: |
          {
            "api": ["apps/api/**"],
            "manager": ["apps/manager/**"]
          }

    - name: Github event
      id: event
      shell: bash
      run: |
        if -e "${{ github.event_name }}" "push"; then
          echo "push=true" >> "$GITHUB_OUTPUT"
          echo "pull=false" >> "$GITHUB_OUTPUT"
        fi

        if -e "${{ github.event_name }}" "pull_request"; then
          echo "push=false" >> "$GITHUB_OUTPUT"
          echo "pull=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Deploy target
      id: deploy
      shell: bash
      run: |
        if -t "${{ steps.event.outputs.push }}"; then
          echo "target=production" >> "$GITHUB_OUTPUT"
        fi

        if -t "${{ steps.event.outputs.pull }}"; then
          echo "target=preview" >> "$GITHUB_OUTPUT"
        fi

    - name: Pull Github event slug
      id: pull
      if: steps.event.outputs.pull == 'true'
      shell: bash
      run: |
        echo "slug=$(
          echo ${{ github.head_ref }} \
          | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9]+/-/g' \
          | sed -E 's/^-+|-+$//g'
        )" >> "$GITHUB_OUTPUT"

    - name: Turbo
      shell: bash
      id: turbo
      run: |
        filter=""

        if -t "${{ steps.paths.outputs.api }}"; then
          filter+=" --filter=@powercoach/api"
        fi

        if -t "${{ steps.paths.outputs.manager }}"; then
          filter+=" --filter=@powercoach/manager"
        fi

        echo "filter=$filter" >> "$GITHUB_OUTPUT"

    - name: CI
      shell: bash
      id: ci
      run: |
        action="false"

        if -t "${{ steps.event.outputs.push }}" &&
           -n "${{ steps.turbo.outputs.filter }}"; then
          action="true"
        fi

        if -t "${{ steps.event.outputs.pull }}" &&
           -e "${{ github.event.pull_request.head.repo.full_name }}" "${{ github.repository }}" &&
           -n "${{ steps.turbo.outputs.filter }}"; then
          action="true"
        fi

        echo "action=$action" >> "$GITHUB_OUTPUT"

    - name: CD
      id: cd
      shell: bash
      run: echo "action=${{ steps.ci.outputs.action }}" >> "$GITHUB_OUTPUT"

    - name: Cutted sha256sum
      id: sha
      shell: bash
      run: |
        cut_flag="-c1-10"

        files_sha() {
          git ls-files -z "$1" \
            | sort -z \
            | xargs -0 sha256sum \
            | sha256sum \
            | cut -d' ' -f1 \
            | cut "$cut_flag"
        }

        echo "api=$(files_sha apps/api)" >> "$GITHUB_OUTPUT"
        echo "manager=$(files_sha apps/manager)" >> "$GITHUB_OUTPUT"

        if -t "${{ steps.event.outputs.pull }}"; then
          echo "branch=$(printf '%s' '${{ github.head_ref }}' | sha256sum | cut $cut_flag)" >> "$GITHUB_OUTPUT"
        fi

        if -t "${{ steps.event.outputs.push }}"; then
          echo "branch=$(printf '%s' '${{ github.ref_name }}' | sha256sum | cut $cut_flag)" >> "$GITHUB_OUTPUT"
        fi

    - uses: ./.github/actions/core/summary
      with:
        title: Context outputs
        data: |
          {
            "API SHA": "${{ steps.sha.outputs.api }}",
            "Branch SHA": "${{ steps.sha.outputs.branch }}",
            "CI action": "${{ steps.ci.outputs.action }}",
            "CD action": "${{ steps.cd.outputs.action }}",
            "Deploy target": "${{ steps.deploy.outputs.target }}",
            "Manager SHA": "${{ steps.sha.outputs.manager }}",
            "Pull event": "${{ steps.event.outputs.pull }}",
            "Pull slug": "${{ steps.pull.outputs.slug }}",
            "Push event": "${{ steps.event.outputs.push }}",
            "Turbo filter": "${{ steps.turbo.outputs.filter }}"
          }

    - uses: ./.github/actions/core/summary
      with:
        title: Context tasks
        layout: 'list'
        level: '4'
        data: |
          {
            "API path": "${{ steps.paths.outputs.api }}",
            "Manager path": "${{ steps.paths.outputs.manager }}"
          }
