name: Find prodded deployment
description: Retrieves prodded deployment from Vercel via the v13 API

inputs:
  project:
    description: Vercel project
    required: true
  team:
    description: Vercel team
    required: true
  token:
    description: Vercel token
    required: true

outputs:
  id:
    description: Deployment ID if found
    value: ${{ steps.find.outputs.id }}
  found:
    description: Whether the deployment has been found
    value: ${{ steps.find.outputs.found }}
  hash:
    description: Deployment hash metadata if found
    value: ${{ steps.find.outputs.hash }}
  host:
    description: Deployment host if found
    value: ${{ steps.find.outputs.host }}

runs:
  using: composite
  steps:
    - name: Production host computation
      id: alias
      uses: ./.github/actions/vercel/alias
      with:
        project: ${{ inputs.project }}
        team: ${{ inputs.team }}

    - name: Find Vercel prodded deployment
      id: find
      shell: bash
      run: |
        echo "ðŸ” Querying Vercel production deployment"

        response=$(
          curl \
            --request GET \
            --header "Authorization: Bearer ${{ inputs.token }}"
            --url "https://api.vercel.com/v13/deployments/${{ steps.alias.outputs.host }}" \
          2>/dev/null \
          | jq -r '{
              id: .id,
              hash: .meta.hash,
              host: .url
            } // empty' \
          || echo ""
        )

        if [[ -n "$response" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
          echo "id=$(echo "$response" | jq -r '.id')" >> "$GITHUB_OUTPUT"
          echo "hash=$(echo "$response" | jq -r '.hash')" >> "$GITHUB_OUTPUT"
          echo "host=$(echo "$response" | jq -r '.host')" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
