name: Manager CD

inputs:
  alias:
    description: Google Cloud Platform revision tag name
    required: false
  api-url:
    description: API URL used during build phase
    required: true
  override-alias:
    description: Force an alias to be rebuilt and deployed
    required: false
    default: 'false'
  project:
    description: Vercel project name
    required: true
  token:
    description: Vercel token
    required: true

outputs:
  url:
    description: Running Manager URL
    value: ${{ steps.alias.outputs.url || steps.deploy.outputs.url }}

runs:
  using: composite
  steps:
    - name: Alias host computation
      if: ${{ inputs.alias != '' }}
      shell: bash
      run: echo "ALIAS_HOST=${{ inputs.alias }}-${{ inputs.project }}.vercel.app" >> "$GITHUB_ENV"

    - name: Alias detection
      if: ${{ inputs.override-alias == 'false' && inputs.alias != '' }}
      id: alias
      shell: bash
      run: |
        list="$(pnpm vercel alias list --limit 100 --token ${{ inputs.token }})"
        host="$(echo "$list" | grep "$ALIAS_HOST" | awk '{print $2}')"

        echo "detected=$([[ "$host" != '' ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"
        echo "url=https://$host" >> "$GITHUB_OUTPUT"

    - name: Build
      if: ${{ steps.alias.outputs.detected != 'true' }}
      shell: bash
      env:
        VITE_API_BASE_URL: ${{ inputs.api-url }}
      run: pnpm --filter=@powercoach/manager build

    - name: Deploy
      if: ${{ steps.alias.outputs.detected != 'true' }}
      shell: bash
      id: deploy
      working-directory: apps/manager/dist
      env:
        VERCEL_TELEMETRY_DISABLED: 1
      run: |
        pnpm vercel link --yes --project ${{ inputs.project }} --token ${{ inputs.token }}

        if ${{ inputs.alias != '' }}; then
          url=$(pnpm vercel deploy --yes --token ${{ inputs.token }})
          pnpm vercel alias set "$url" "$ALIAS_HOST" --token ${{ inputs.token }}
          echo "url=https://$ALIAS_HOST" >> "$GITHUB_OUTPUT"
        else
          url=$(pnpm vercel deploy --yes --prod --token ${{ inputs.token }})
          echo "url=https://$url" >> "$GITHUB_OUTPUT"
        fi
