name: Initialize project

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      with:
        run_install: false

    - name: Determine pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: ${{ steps.pnpm-store.outputs.dir }}
        key: pnpm-store-${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-node-${{ inputs.node-version }}-
          pnpm-store-${{ runner.os }}-

    - name: Use Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Turbo
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: |
          node_modules/.cache/turbo
          .turbo
        key: turbo-${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
        restore-keys: |
          turbo-${{ runner.os }}-node-${{ inputs.node-version }}-
          turbo-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
