name: Install
description: Install all the tools to execute Powercoach app tasks

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Determine pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.dir }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json

    - name: Cache Turbo
      uses: actions/cache@v4
      with:
        path: |
          node_modules/.cache/turbo
          .turbo
        key: turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
        restore-keys: |
          turbo-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Add binaries to PATH
      shell: bash
      run: |
        echo "PATH=${{ github.workspace }}/node_modules/.bin:$PATH" >> "$GITHUB_ENV"
        echo "PATH=${{ github.workspace }}/apps/api/node_modules/.bin:$PATH" >> "$GITHUB_ENV"
        echo "PATH=${{ github.workspace }}/apps/manager/node_modules/.bin:$PATH" >> "$GITHUB_ENV"
