name: CI

on:
  workflow_call:
    inputs:
      ci-filters:
        description: CI filters passed to pnpm commands
        type: string
        required: true
    outputs:
      api-hash:
        description: Hash of the API source directory
        value: ${{ jobs.CI.outputs.api-hash }}
      manager-hash:
        description: Hash of the Manager source directory
        value: ${{ jobs.CI.outputs.manager-hash }}

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  CI:
    runs-on: ubuntu-latest
    name: Lint, Format, Typecheck, Test
    outputs:
      api-hash: ${{ steps.hash.outputs.api }}
      manager-hash: ${{ steps.hash.outputs.manager }}
    env:
      CI_FILTERS: ${{ inputs.ci-filters }}
    steps:
      - name: Inputs
        shell: bash
        run: |
          {
            echo "## CI inputs"
            echo ""
            echo "| Key | Value |"
            echo "| --- | --- |"
            echo "| CI filters | ${CI_FILTERS=-'❌'} |"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Lint
        run: pnpm lint $CI_FILTERS

      - name: Format
        run: pnpm format $CI_FILTERS

      - name: Typecheck
        run: pnpm typecheck $CI_FILTERS

      - name: Test
        run: pnpm test $CI_FILTERS

      - name: Hash
        id: hash
        shell: bash
        run: |
          hash() {
            git ls-files -z "$1" \
              | sort -z \
              | xargs -0 sha256sum \
              | sha256sum \
              | cut -d' ' -f1
          }

          [[ "$CI_FILTERS" == *"api"* ]] && echo "api=$(hash apps/api)" >> "$GITHUB_OUTPUT"
          [[ "$CI_FILTERS" == *"manager"* ]] && echo "manager=$(hash apps/manager)" >> "$GITHUB_OUTPUT"

      - name: Outputs
        shell: bash
        run: |
          {
            echo "## CI outputs"
            echo ""
            echo "| Key | Value |"
            echo "| --- | --- |"
            echo "| API hash | ${{ steps.hash.outputs.api || '❌' }} |"
            echo "| Manager hash | ${{ steps.hash.outputs.manager || '❌' }} |"
            echo ""
            echo "#### CI steps"
            echo ""
            echo "- ✨ Lint ⇒ ✅"
            echo "- 💅 Format ⇒ ✅"
            echo "- 🛡️ Typecheck ⇒ ✅"
            echo "- 🧪 Test ⇒ ✅"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"
