name: Powercoach

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'apps/manager/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  powercoach:
    name: Powercoach CI & CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/powercoach/context
      - uses: ./.github/actions/powercoach/install
      - uses: ./.github/actions/powercoach/ci
      - uses: ./.github/actions/powercoach/cd
      - uses: ./.github/actions/powercoach/summary
